// FULL_A RAW processing, 125 MHz. Source samples are followed by 62 valid
// zeros injected AFTER RX calibration, then the FD/target registers drain.
// phase_i/q describe the FD-output sample at the current target-input edge;
// they are not silently shifted from RAW-input time or generated by the host.
module replay_processing_chain(
 input wire clk,rst,profile_commit,hard_fault,
 input wire [1:0] shadow_cal_valid,input wire [63:0] shadow_dc,
 input wire [71:0] shadow_gain,input wire [143:0] shadow_matrix,
 input wire [7:0] shadow_fd_phase,input wire [31:0] shadow_fd_version,
 input wire phase_valid,input wire signed [17:0] phase_i,phase_q,
 input wire in_valid,in_last,input wire [63:0] in_hv,
 output wire profile_ready,output reg profile_accepted,profile_rejected,
 output wire source_ready,busy,output reg done,cancelled,
 output wire [63:0] out_hv,output wire out_valid,out_qualified,
 output reg arithmetic_saturated,output wire [31:0] table_version
);
 localparam IDLE=0,STREAM=1,FLUSH=2,DRAIN=3;
 reg [1:0] state;reg configured;
 reg [63:0] dc;reg [71:0] gain;reg [143:0] matrix;
 reg [6:0] flush_left;reg [3:0] drain_left;
 wire [1:0] cal_valid,cal_good,cal_sat,fd_valid,fd_good,fd_sat;
 wire [63:0] calibrated,delayed,target_data;
 wire target_valid,target_good,target_sat;
 assign profile_ready=state==IDLE&&!(|cal_valid)&&!rst&&!hard_fault;
 wire configure=profile_commit&&profile_ready&&(&shadow_cal_valid)&&shadow_fd_version==table_version;
 assign source_ready=configured&&!cancelled&&!hard_fault&&!rst&&!profile_commit&&(state==IDLE||state==STREAM);
 wire accept_input=in_valid&&source_ready;
 wire inject_zero=state==FLUSH&&!(|cal_valid)&&flush_left!=0;
 wire fd_input_valid=(&cal_valid)||inject_zero;
 assign busy=state!=IDLE;
 assign out_valid=target_valid&&!cancelled&&!hard_fault&&!rst;
 assign out_qualified=out_valid&&target_good;
 assign out_hv=out_qualified?target_data:64'd0;
 genvar lane;
 generate for(lane=0;lane<2;lane=lane+1)begin: hv
  rx_cal_executor cal(.clk(clk),.rst(rst),.in_valid(accept_input),.cal_valid(configured),
   .in_i(in_hv[lane*32+:16]),.in_q(in_hv[lane*32+16+:16]),
   .dc_i(dc[lane*32+:16]),.dc_q(dc[lane*32+16+:16]),
   .gain_i(gain[lane*36+:18]),.gain_q(gain[lane*36+18+:18]),
   .out_valid(cal_valid[lane]),.out_cal_valid(cal_good[lane]),
   .out_i(calibrated[lane*32+:16]),.out_q(calibrated[lane*32+16+:16]),.saturated(cal_sat[lane]));
  wire [31:0] version;
  fractional_delay_profile fd(.clk(clk),.rst(rst),.in_valid(fd_input_valid),
   .profile_commit(configure),.safe_boundary(profile_ready),.shadow_phase(shadow_fd_phase),.shadow_version(shadow_fd_version),
   .in_i(inject_zero?16'd0:calibrated[lane*32+:16]),.in_q(inject_zero?16'd0:calibrated[lane*32+16+:16]),
   .out_valid(fd_valid[lane]),.out_coeff_valid(fd_good[lane]),.saturated(fd_sat[lane]),
   .out_i(delayed[lane*32+:16]),.out_q(delayed[lane*32+16+:16]),
   .commit_ack(),.commit_rejected(),.active_phase(),.active_version(),.table_version(version));
  if(lane==0)assign table_version=version;
 end endgenerate
 target_complex_operator target(.clk(clk),.rst(rst),.in_valid(&fd_valid),
  .model_valid((&fd_good)&&phase_valid),.in_hv(delayed),.matrix(matrix),.phase_i(phase_i),.phase_q(phase_q),
  .out_valid(target_valid),.out_model_valid(target_good),.out_hv(target_data),.saturated(target_sat));
 always @(posedge clk)begin
  if(rst)begin
   state<=IDLE;configured<=0;cancelled<=0;dc<=0;gain<=0;matrix<=0;flush_left<=0;drain_left<=0;
   done<=0;profile_accepted<=0;profile_rejected<=0;arithmetic_saturated<=0;
  end else begin
   done<=0;profile_accepted<=configure;profile_rejected<=profile_commit&&!configure;
   if(configure)begin configured<=1;dc<=shadow_dc;gain<=shadow_gain;matrix<=shadow_matrix;cancelled<=0;arithmetic_saturated<=0;end
   else if((|cal_sat)||(|fd_sat)||target_sat)arithmetic_saturated<=1;
   if(accept_input)begin
    if(state==IDLE)arithmetic_saturated<=0;
    if(in_last)begin state<=FLUSH;flush_left<=62;end
    else state<=STREAM;
   end
   if(state==FLUSH&&inject_zero)begin
    flush_left<=flush_left-1'b1;
    if(flush_left==1)begin state<=DRAIN;drain_left<=10;end
   end
   if(state==DRAIN)begin
    if(drain_left!=0)drain_left<=drain_left-1'b1;
    else begin state<=IDLE;done<=!cancelled;end
   end
   if(hard_fault&&!cancelled)begin
    cancelled<=1;
    if(state==STREAM)begin state<=FLUSH;flush_left<=62;end
   end
  end
 end
endmodule
