// Generated by tools/generate_fir_rtl.py; do not hand edit.
// Coefficient JSON SHA256 8523fcf1018f481f2ea01615446bc633dd570d2a60e78a198afa341b22405597
// Lane 0 is earliest. Valid gaps preserve sample history; reset clears history/valid.
// RX_FIR75_D2: source COE SHA256 1e0572249ab3ccd15a45362bdefbf8ec3d658433ae37df58d3a7c366f296479b
// Pipeline: registered preadd, multiply, 6 balanced sum levels, round/saturate.
// 9 registers; accepted edge n -> output edge n+8; II=1.
module fir_rx_fir75(input wire clk,rst,in_valid,
 input wire [47:0] in_data, output wire out_valid,
 output reg [15:0] out_data, output reg [0:0] out_sat);
 reg signed [23:0] history[0:74];
 reg [8:0] valid_pipe;
 integer h;
 always @(posedge clk) begin
   if(rst) begin
     valid_pipe <= 0;
     for(h=0;h<75;h=h+1) history[h]<=0;
   end else begin
     valid_pipe <= {valid_pipe[7:0],in_valid};
     if(in_valid) begin
       history[0] <= in_data[24 +: 24];
       history[1] <= in_data[0 +: 24];
       history[2] <= history[0];
       history[3] <= history[1];
       history[4] <= history[2];
       history[5] <= history[3];
       history[6] <= history[4];
       history[7] <= history[5];
       history[8] <= history[6];
       history[9] <= history[7];
       history[10] <= history[8];
       history[11] <= history[9];
       history[12] <= history[10];
       history[13] <= history[11];
       history[14] <= history[12];
       history[15] <= history[13];
       history[16] <= history[14];
       history[17] <= history[15];
       history[18] <= history[16];
       history[19] <= history[17];
       history[20] <= history[18];
       history[21] <= history[19];
       history[22] <= history[20];
       history[23] <= history[21];
       history[24] <= history[22];
       history[25] <= history[23];
       history[26] <= history[24];
       history[27] <= history[25];
       history[28] <= history[26];
       history[29] <= history[27];
       history[30] <= history[28];
       history[31] <= history[29];
       history[32] <= history[30];
       history[33] <= history[31];
       history[34] <= history[32];
       history[35] <= history[33];
       history[36] <= history[34];
       history[37] <= history[35];
       history[38] <= history[36];
       history[39] <= history[37];
       history[40] <= history[38];
       history[41] <= history[39];
       history[42] <= history[40];
       history[43] <= history[41];
       history[44] <= history[42];
       history[45] <= history[43];
       history[46] <= history[44];
       history[47] <= history[45];
       history[48] <= history[46];
       history[49] <= history[47];
       history[50] <= history[48];
       history[51] <= history[49];
       history[52] <= history[50];
       history[53] <= history[51];
       history[54] <= history[52];
       history[55] <= history[53];
       history[56] <= history[54];
       history[57] <= history[55];
       history[58] <= history[56];
       history[59] <= history[57];
       history[60] <= history[58];
       history[61] <= history[59];
       history[62] <= history[60];
       history[63] <= history[61];
       history[64] <= history[62];
       history[65] <= history[63];
       history[66] <= history[64];
       history[67] <= history[65];
       history[68] <= history[66];
       history[69] <= history[67];
       history[70] <= history[68];
       history[71] <= history[69];
       history[72] <= history[70];
       history[73] <= history[71];
       history[74] <= history[72];
     end
   end
 end
 assign out_valid=valid_pipe[8];
 wire signed [23:0] a0_0 = $signed(in_data[0 +: 24]);
 wire signed [23:0] b0_0 = history[73];
 reg signed [24:0] pre0_0;
 (* use_dsp="yes" *) reg signed [47:0] prod0_0;
 always @(posedge clk) begin
   pre0_0 <= $signed({a0_0[23],a0_0}) + $signed({b0_0[23],b0_0});
   prod0_0 <= pre0_0 * 18'sd13;
 end
 wire signed [23:0] a0_1 = history[0];
 wire signed [23:0] b0_1 = history[72];
 reg signed [24:0] pre0_1;
 (* use_dsp="yes" *) reg signed [47:0] prod0_1;
 always @(posedge clk) begin
   pre0_1 <= $signed({a0_1[23],a0_1}) + $signed({b0_1[23],b0_1});
   prod0_1 <= pre0_1 * -18'sd40;
 end
 wire signed [23:0] a0_2 = history[1];
 wire signed [23:0] b0_2 = history[71];
 reg signed [24:0] pre0_2;
 (* use_dsp="yes" *) reg signed [47:0] prod0_2;
 always @(posedge clk) begin
   pre0_2 <= $signed({a0_2[23],a0_2}) + $signed({b0_2[23],b0_2});
   prod0_2 <= pre0_2 * -18'sd88;
 end
 wire signed [23:0] a0_3 = history[2];
 wire signed [23:0] b0_3 = history[70];
 reg signed [24:0] pre0_3;
 (* use_dsp="yes" *) reg signed [47:0] prod0_3;
 always @(posedge clk) begin
   pre0_3 <= $signed({a0_3[23],a0_3}) + $signed({b0_3[23],b0_3});
   prod0_3 <= pre0_3 * -18'sd32;
 end
 wire signed [23:0] a0_4 = history[3];
 wire signed [23:0] b0_4 = history[69];
 reg signed [24:0] pre0_4;
 (* use_dsp="yes" *) reg signed [47:0] prod0_4;
 always @(posedge clk) begin
   pre0_4 <= $signed({a0_4[23],a0_4}) + $signed({b0_4[23],b0_4});
   prod0_4 <= pre0_4 * 18'sd95;
 end
 wire signed [23:0] a0_5 = history[4];
 wire signed [23:0] b0_5 = history[68];
 reg signed [24:0] pre0_5;
 (* use_dsp="yes" *) reg signed [47:0] prod0_5;
 always @(posedge clk) begin
   pre0_5 <= $signed({a0_5[23],a0_5}) + $signed({b0_5[23],b0_5});
   prod0_5 <= pre0_5 * 18'sd85;
 end
 wire signed [23:0] a0_6 = history[5];
 wire signed [23:0] b0_6 = history[67];
 reg signed [24:0] pre0_6;
 (* use_dsp="yes" *) reg signed [47:0] prod0_6;
 always @(posedge clk) begin
   pre0_6 <= $signed({a0_6[23],a0_6}) + $signed({b0_6[23],b0_6});
   prod0_6 <= pre0_6 * -18'sd107;
 end
 wire signed [23:0] a0_7 = history[6];
 wire signed [23:0] b0_7 = history[66];
 reg signed [24:0] pre0_7;
 (* use_dsp="yes" *) reg signed [47:0] prod0_7;
 always @(posedge clk) begin
   pre0_7 <= $signed({a0_7[23],a0_7}) + $signed({b0_7[23],b0_7});
   prod0_7 <= pre0_7 * -18'sd177;
 end
 wire signed [23:0] a0_8 = history[7];
 wire signed [23:0] b0_8 = history[65];
 reg signed [24:0] pre0_8;
 (* use_dsp="yes" *) reg signed [47:0] prod0_8;
 always @(posedge clk) begin
   pre0_8 <= $signed({a0_8[23],a0_8}) + $signed({b0_8[23],b0_8});
   prod0_8 <= pre0_8 * 18'sd78;
 end
 wire signed [23:0] a0_9 = history[8];
 wire signed [23:0] b0_9 = history[64];
 reg signed [24:0] pre0_9;
 (* use_dsp="yes" *) reg signed [47:0] prod0_9;
 always @(posedge clk) begin
   pre0_9 <= $signed({a0_9[23],a0_9}) + $signed({b0_9[23],b0_9});
   prod0_9 <= pre0_9 * 18'sd288;
 end
 wire signed [23:0] a0_10 = history[9];
 wire signed [23:0] b0_10 = history[63];
 reg signed [24:0] pre0_10;
 (* use_dsp="yes" *) reg signed [47:0] prod0_10;
 always @(posedge clk) begin
   pre0_10 <= $signed({a0_10[23],a0_10}) + $signed({b0_10[23],b0_10});
   prod0_10 <= pre0_10 * 18'sd15;
 end
 wire signed [23:0] a0_11 = history[10];
 wire signed [23:0] b0_11 = history[62];
 reg signed [24:0] pre0_11;
 (* use_dsp="yes" *) reg signed [47:0] prod0_11;
 always @(posedge clk) begin
   pre0_11 <= $signed({a0_11[23],a0_11}) + $signed({b0_11[23],b0_11});
   prod0_11 <= pre0_11 * -18'sd396;
 end
 wire signed [23:0] a0_12 = history[11];
 wire signed [23:0] b0_12 = history[61];
 reg signed [24:0] pre0_12;
 (* use_dsp="yes" *) reg signed [47:0] prod0_12;
 always @(posedge clk) begin
   pre0_12 <= $signed({a0_12[23],a0_12}) + $signed({b0_12[23],b0_12});
   prod0_12 <= pre0_12 * -18'sd186;
 end
 wire signed [23:0] a0_13 = history[12];
 wire signed [23:0] b0_13 = history[60];
 reg signed [24:0] pre0_13;
 (* use_dsp="yes" *) reg signed [47:0] prod0_13;
 always @(posedge clk) begin
   pre0_13 <= $signed({a0_13[23],a0_13}) + $signed({b0_13[23],b0_13});
   prod0_13 <= pre0_13 * 18'sd461;
 end
 wire signed [23:0] a0_14 = history[13];
 wire signed [23:0] b0_14 = history[59];
 reg signed [24:0] pre0_14;
 (* use_dsp="yes" *) reg signed [47:0] prod0_14;
 always @(posedge clk) begin
   pre0_14 <= $signed({a0_14[23],a0_14}) + $signed({b0_14[23],b0_14});
   prod0_14 <= pre0_14 * 18'sd439;
 end
 wire signed [23:0] a0_15 = history[14];
 wire signed [23:0] b0_15 = history[58];
 reg signed [24:0] pre0_15;
 (* use_dsp="yes" *) reg signed [47:0] prod0_15;
 always @(posedge clk) begin
   pre0_15 <= $signed({a0_15[23],a0_15}) + $signed({b0_15[23],b0_15});
   prod0_15 <= pre0_15 * -18'sd437;
 end
 wire signed [23:0] a0_16 = history[15];
 wire signed [23:0] b0_16 = history[57];
 reg signed [24:0] pre0_16;
 (* use_dsp="yes" *) reg signed [47:0] prod0_16;
 always @(posedge clk) begin
   pre0_16 <= $signed({a0_16[23],a0_16}) + $signed({b0_16[23],b0_16});
   prod0_16 <= pre0_16 * -18'sd757;
 end
 wire signed [23:0] a0_17 = history[16];
 wire signed [23:0] b0_17 = history[56];
 reg signed [24:0] pre0_17;
 (* use_dsp="yes" *) reg signed [47:0] prod0_17;
 always @(posedge clk) begin
   pre0_17 <= $signed({a0_17[23],a0_17}) + $signed({b0_17[23],b0_17});
   prod0_17 <= pre0_17 * 18'sd272;
 end
 wire signed [23:0] a0_18 = history[17];
 wire signed [23:0] b0_18 = history[55];
 reg signed [24:0] pre0_18;
 (* use_dsp="yes" *) reg signed [47:0] prod0_18;
 always @(posedge clk) begin
   pre0_18 <= $signed({a0_18[23],a0_18}) + $signed({b0_18[23],b0_18});
   prod0_18 <= pre0_18 * 18'sd1094;
 end
 wire signed [23:0] a0_19 = history[18];
 wire signed [23:0] b0_19 = history[54];
 reg signed [24:0] pre0_19;
 (* use_dsp="yes" *) reg signed [47:0] prod0_19;
 always @(posedge clk) begin
   pre0_19 <= $signed({a0_19[23],a0_19}) + $signed({b0_19[23],b0_19});
   prod0_19 <= pre0_19 * 18'sd79;
 end
 wire signed [23:0] a0_20 = history[19];
 wire signed [23:0] b0_20 = history[53];
 reg signed [24:0] pre0_20;
 (* use_dsp="yes" *) reg signed [47:0] prod0_20;
 always @(posedge clk) begin
   pre0_20 <= $signed({a0_20[23],a0_20}) + $signed({b0_20[23],b0_20});
   prod0_20 <= pre0_20 * -18'sd1383;
 end
 wire signed [23:0] a0_21 = history[20];
 wire signed [23:0] b0_21 = history[52];
 reg signed [24:0] pre0_21;
 (* use_dsp="yes" *) reg signed [47:0] prod0_21;
 always @(posedge clk) begin
   pre0_21 <= $signed({a0_21[23],a0_21}) + $signed({b0_21[23],b0_21});
   prod0_21 <= pre0_21 * -18'sd641;
 end
 wire signed [23:0] a0_22 = history[21];
 wire signed [23:0] b0_22 = history[51];
 reg signed [24:0] pre0_22;
 (* use_dsp="yes" *) reg signed [47:0] prod0_22;
 always @(posedge clk) begin
   pre0_22 <= $signed({a0_22[23],a0_22}) + $signed({b0_22[23],b0_22});
   prod0_22 <= pre0_22 * 18'sd1527;
 end
 wire signed [23:0] a0_23 = history[22];
 wire signed [23:0] b0_23 = history[50];
 reg signed [24:0] pre0_23;
 (* use_dsp="yes" *) reg signed [47:0] prod0_23;
 always @(posedge clk) begin
   pre0_23 <= $signed({a0_23[23],a0_23}) + $signed({b0_23[23],b0_23});
   prod0_23 <= pre0_23 * 18'sd1417;
 end
 wire signed [23:0] a0_24 = history[23];
 wire signed [23:0] b0_24 = history[49];
 reg signed [24:0] pre0_24;
 (* use_dsp="yes" *) reg signed [47:0] prod0_24;
 always @(posedge clk) begin
   pre0_24 <= $signed({a0_24[23],a0_24}) + $signed({b0_24[23],b0_24});
   prod0_24 <= pre0_24 * -18'sd1413;
 end
 wire signed [23:0] a0_25 = history[24];
 wire signed [23:0] b0_25 = history[48];
 reg signed [24:0] pre0_25;
 (* use_dsp="yes" *) reg signed [47:0] prod0_25;
 always @(posedge clk) begin
   pre0_25 <= $signed({a0_25[23],a0_25}) + $signed({b0_25[23],b0_25});
   prod0_25 <= pre0_25 * -18'sd2373;
 end
 wire signed [23:0] a0_26 = history[25];
 wire signed [23:0] b0_26 = history[47];
 reg signed [24:0] pre0_26;
 (* use_dsp="yes" *) reg signed [47:0] prod0_26;
 always @(posedge clk) begin
   pre0_26 <= $signed({a0_26[23],a0_26}) + $signed({b0_26[23],b0_26});
   prod0_26 <= pre0_26 * 18'sd906;
 end
 wire signed [23:0] a0_27 = history[26];
 wire signed [23:0] b0_27 = history[46];
 reg signed [24:0] pre0_27;
 (* use_dsp="yes" *) reg signed [47:0] prod0_27;
 always @(posedge clk) begin
   pre0_27 <= $signed({a0_27[23],a0_27}) + $signed({b0_27[23],b0_27});
   prod0_27 <= pre0_27 * 18'sd3446;
 end
 wire signed [23:0] a0_28 = history[27];
 wire signed [23:0] b0_28 = history[45];
 reg signed [24:0] pre0_28;
 (* use_dsp="yes" *) reg signed [47:0] prod0_28;
 always @(posedge clk) begin
   pre0_28 <= $signed({a0_28[23],a0_28}) + $signed({b0_28[23],b0_28});
   prod0_28 <= pre0_28 * 18'sd156;
 end
 wire signed [23:0] a0_29 = history[28];
 wire signed [23:0] b0_29 = history[44];
 reg signed [24:0] pre0_29;
 (* use_dsp="yes" *) reg signed [47:0] prod0_29;
 always @(posedge clk) begin
   pre0_29 <= $signed({a0_29[23],a0_29}) + $signed({b0_29[23],b0_29});
   prod0_29 <= pre0_29 * -18'sd4544;
 end
 wire signed [23:0] a0_30 = history[29];
 wire signed [23:0] b0_30 = history[43];
 reg signed [24:0] pre0_30;
 (* use_dsp="yes" *) reg signed [47:0] prod0_30;
 always @(posedge clk) begin
   pre0_30 <= $signed({a0_30[23],a0_30}) + $signed({b0_30[23],b0_30});
   prod0_30 <= pre0_30 * -18'sd2024;
 end
 wire signed [23:0] a0_31 = history[30];
 wire signed [23:0] b0_31 = history[42];
 reg signed [24:0] pre0_31;
 (* use_dsp="yes" *) reg signed [47:0] prod0_31;
 always @(posedge clk) begin
   pre0_31 <= $signed({a0_31[23],a0_31}) + $signed({b0_31[23],b0_31});
   prod0_31 <= pre0_31 * 18'sd5558;
 end
 wire signed [23:0] a0_32 = history[31];
 wire signed [23:0] b0_32 = history[41];
 reg signed [24:0] pre0_32;
 (* use_dsp="yes" *) reg signed [47:0] prod0_32;
 always @(posedge clk) begin
   pre0_32 <= $signed({a0_32[23],a0_32}) + $signed({b0_32[23],b0_32});
   prod0_32 <= pre0_32 * 18'sd5268;
 end
 wire signed [23:0] a0_33 = history[32];
 wire signed [23:0] b0_33 = history[40];
 reg signed [24:0] pre0_33;
 (* use_dsp="yes" *) reg signed [47:0] prod0_33;
 always @(posedge clk) begin
   pre0_33 <= $signed({a0_33[23],a0_33}) + $signed({b0_33[23],b0_33});
   prod0_33 <= pre0_33 * -18'sd6380;
 end
 wire signed [23:0] a0_34 = history[33];
 wire signed [23:0] b0_34 = history[39];
 reg signed [24:0] pre0_34;
 (* use_dsp="yes" *) reg signed [47:0] prod0_34;
 always @(posedge clk) begin
   pre0_34 <= $signed({a0_34[23],a0_34}) + $signed({b0_34[23],b0_34});
   prod0_34 <= pre0_34 * -18'sd11956;
 end
 wire signed [23:0] a0_35 = history[34];
 wire signed [23:0] b0_35 = history[38];
 reg signed [24:0] pre0_35;
 (* use_dsp="yes" *) reg signed [47:0] prod0_35;
 always @(posedge clk) begin
   pre0_35 <= $signed({a0_35[23],a0_35}) + $signed({b0_35[23],b0_35});
   prod0_35 <= pre0_35 * 18'sd6915;
 end
 wire signed [23:0] a0_36 = history[35];
 wire signed [23:0] b0_36 = history[37];
 reg signed [24:0] pre0_36;
 (* use_dsp="yes" *) reg signed [47:0] prod0_36;
 always @(posedge clk) begin
   pre0_36 <= $signed({a0_36[23],a0_36}) + $signed({b0_36[23],b0_36});
   prod0_36 <= pre0_36 * 18'sd41098;
 end
 wire signed [23:0] a0_37 = history[36];
 wire signed [23:0] b0_37 = 0;
 reg signed [24:0] pre0_37;
 (* use_dsp="yes" *) reg signed [47:0] prod0_37;
 always @(posedge clk) begin
   pre0_37 <= $signed({a0_37[23],a0_37}) + $signed({b0_37[23],b0_37});
   prod0_37 <= pre0_37 * 18'sd58518;
 end
 reg signed [47:0] sum0_0_0;
 always @(posedge clk) sum0_0_0 <= prod0_0 + prod0_1;
 reg signed [47:0] sum0_0_1;
 always @(posedge clk) sum0_0_1 <= prod0_2 + prod0_3;
 reg signed [47:0] sum0_0_2;
 always @(posedge clk) sum0_0_2 <= prod0_4 + prod0_5;
 reg signed [47:0] sum0_0_3;
 always @(posedge clk) sum0_0_3 <= prod0_6 + prod0_7;
 reg signed [47:0] sum0_0_4;
 always @(posedge clk) sum0_0_4 <= prod0_8 + prod0_9;
 reg signed [47:0] sum0_0_5;
 always @(posedge clk) sum0_0_5 <= prod0_10 + prod0_11;
 reg signed [47:0] sum0_0_6;
 always @(posedge clk) sum0_0_6 <= prod0_12 + prod0_13;
 reg signed [47:0] sum0_0_7;
 always @(posedge clk) sum0_0_7 <= prod0_14 + prod0_15;
 reg signed [47:0] sum0_0_8;
 always @(posedge clk) sum0_0_8 <= prod0_16 + prod0_17;
 reg signed [47:0] sum0_0_9;
 always @(posedge clk) sum0_0_9 <= prod0_18 + prod0_19;
 reg signed [47:0] sum0_0_10;
 always @(posedge clk) sum0_0_10 <= prod0_20 + prod0_21;
 reg signed [47:0] sum0_0_11;
 always @(posedge clk) sum0_0_11 <= prod0_22 + prod0_23;
 reg signed [47:0] sum0_0_12;
 always @(posedge clk) sum0_0_12 <= prod0_24 + prod0_25;
 reg signed [47:0] sum0_0_13;
 always @(posedge clk) sum0_0_13 <= prod0_26 + prod0_27;
 reg signed [47:0] sum0_0_14;
 always @(posedge clk) sum0_0_14 <= prod0_28 + prod0_29;
 reg signed [47:0] sum0_0_15;
 always @(posedge clk) sum0_0_15 <= prod0_30 + prod0_31;
 reg signed [47:0] sum0_0_16;
 always @(posedge clk) sum0_0_16 <= prod0_32 + prod0_33;
 reg signed [47:0] sum0_0_17;
 always @(posedge clk) sum0_0_17 <= prod0_34 + prod0_35;
 reg signed [47:0] sum0_0_18;
 always @(posedge clk) sum0_0_18 <= prod0_36 + prod0_37;
 reg signed [47:0] sum0_0_19;
 always @(posedge clk) sum0_0_19 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_20;
 always @(posedge clk) sum0_0_20 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_21;
 always @(posedge clk) sum0_0_21 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_22;
 always @(posedge clk) sum0_0_22 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_23;
 always @(posedge clk) sum0_0_23 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_24;
 always @(posedge clk) sum0_0_24 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_25;
 always @(posedge clk) sum0_0_25 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_26;
 always @(posedge clk) sum0_0_26 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_27;
 always @(posedge clk) sum0_0_27 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_28;
 always @(posedge clk) sum0_0_28 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_29;
 always @(posedge clk) sum0_0_29 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_30;
 always @(posedge clk) sum0_0_30 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_31;
 always @(posedge clk) sum0_0_31 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_1_0;
 always @(posedge clk) sum0_1_0 <= sum0_0_0 + sum0_0_1;
 reg signed [47:0] sum0_1_1;
 always @(posedge clk) sum0_1_1 <= sum0_0_2 + sum0_0_3;
 reg signed [47:0] sum0_1_2;
 always @(posedge clk) sum0_1_2 <= sum0_0_4 + sum0_0_5;
 reg signed [47:0] sum0_1_3;
 always @(posedge clk) sum0_1_3 <= sum0_0_6 + sum0_0_7;
 reg signed [47:0] sum0_1_4;
 always @(posedge clk) sum0_1_4 <= sum0_0_8 + sum0_0_9;
 reg signed [47:0] sum0_1_5;
 always @(posedge clk) sum0_1_5 <= sum0_0_10 + sum0_0_11;
 reg signed [47:0] sum0_1_6;
 always @(posedge clk) sum0_1_6 <= sum0_0_12 + sum0_0_13;
 reg signed [47:0] sum0_1_7;
 always @(posedge clk) sum0_1_7 <= sum0_0_14 + sum0_0_15;
 reg signed [47:0] sum0_1_8;
 always @(posedge clk) sum0_1_8 <= sum0_0_16 + sum0_0_17;
 reg signed [47:0] sum0_1_9;
 always @(posedge clk) sum0_1_9 <= sum0_0_18 + sum0_0_19;
 reg signed [47:0] sum0_1_10;
 always @(posedge clk) sum0_1_10 <= sum0_0_20 + sum0_0_21;
 reg signed [47:0] sum0_1_11;
 always @(posedge clk) sum0_1_11 <= sum0_0_22 + sum0_0_23;
 reg signed [47:0] sum0_1_12;
 always @(posedge clk) sum0_1_12 <= sum0_0_24 + sum0_0_25;
 reg signed [47:0] sum0_1_13;
 always @(posedge clk) sum0_1_13 <= sum0_0_26 + sum0_0_27;
 reg signed [47:0] sum0_1_14;
 always @(posedge clk) sum0_1_14 <= sum0_0_28 + sum0_0_29;
 reg signed [47:0] sum0_1_15;
 always @(posedge clk) sum0_1_15 <= sum0_0_30 + sum0_0_31;
 reg signed [47:0] sum0_2_0;
 always @(posedge clk) sum0_2_0 <= sum0_1_0 + sum0_1_1;
 reg signed [47:0] sum0_2_1;
 always @(posedge clk) sum0_2_1 <= sum0_1_2 + sum0_1_3;
 reg signed [47:0] sum0_2_2;
 always @(posedge clk) sum0_2_2 <= sum0_1_4 + sum0_1_5;
 reg signed [47:0] sum0_2_3;
 always @(posedge clk) sum0_2_3 <= sum0_1_6 + sum0_1_7;
 reg signed [47:0] sum0_2_4;
 always @(posedge clk) sum0_2_4 <= sum0_1_8 + sum0_1_9;
 reg signed [47:0] sum0_2_5;
 always @(posedge clk) sum0_2_5 <= sum0_1_10 + sum0_1_11;
 reg signed [47:0] sum0_2_6;
 always @(posedge clk) sum0_2_6 <= sum0_1_12 + sum0_1_13;
 reg signed [47:0] sum0_2_7;
 always @(posedge clk) sum0_2_7 <= sum0_1_14 + sum0_1_15;
 reg signed [47:0] sum0_3_0;
 always @(posedge clk) sum0_3_0 <= sum0_2_0 + sum0_2_1;
 reg signed [47:0] sum0_3_1;
 always @(posedge clk) sum0_3_1 <= sum0_2_2 + sum0_2_3;
 reg signed [47:0] sum0_3_2;
 always @(posedge clk) sum0_3_2 <= sum0_2_4 + sum0_2_5;
 reg signed [47:0] sum0_3_3;
 always @(posedge clk) sum0_3_3 <= sum0_2_6 + sum0_2_7;
 reg signed [47:0] sum0_4_0;
 always @(posedge clk) sum0_4_0 <= sum0_3_0 + sum0_3_1;
 reg signed [47:0] sum0_4_1;
 always @(posedge clk) sum0_4_1 <= sum0_3_2 + sum0_3_3;
 reg signed [47:0] sum0_5_0;
 always @(posedge clk) sum0_5_0 <= sum0_4_0 + sum0_4_1;
 wire signed [15:0] q0; wire sat0;
 fir_quantize #(.SHIFT(23),.BITS(16)) qnt0(.value(sum0_5_0),.result(q0),.sat(sat0));
 always @(posedge clk) begin
   if(rst) begin out_data[0 +: 16]<=0; out_sat[0]<=0; end
   else begin out_data[0 +: 16]<=q0; out_sat[0]<=sat0; end
 end
endmodule
