// Generated by tools/generate_fir_rtl.py; do not hand edit.
// Coefficient JSON SHA256 8523fcf1018f481f2ea01615446bc633dd570d2a60e78a198afa341b22405597
// Arithmetic floor plus unsigned residue implements convergent rounding for both signs.
module fir_quantize #(parameter integer SHIFT=17, BITS=16)(
 input wire signed [47:0] value, output wire signed [BITS-1:0] result, output wire sat);
 wire signed [48:0] base = $signed(value) >>> SHIFT;
 wire up = (value[SHIFT-1:0] > (48'd1 << (SHIFT-1))) ||
           ((value[SHIFT-1:0] == (48'd1 << (SHIFT-1))) && base[0]);
 wire signed [48:0] rounded = base + $signed({48'd0,up});
 localparam signed [48:0] HI = (49'sd1 << (BITS-1))-1;
 localparam signed [48:0] LO = -(49'sd1 << (BITS-1));
 assign sat = rounded > HI || rounded < LO;
 assign result = rounded > HI ? HI[BITS-1:0] : rounded < LO ? LO[BITS-1:0] : rounded[BITS-1:0];
endmodule
