/* Generated */
#ifndef AUX_METADATA_H
#define AUX_METADATA_H
#define AUX_META_MAGIC 1096112177u
#define AUX_META_VERSION 1u
#define AUX_META_BYTES 96u
#define AUX_META_MAGIC_OFFSET 0u
#define AUX_META_VERSION_OFFSET 4u
#define AUX_META_BYTES_OFFSET 6u
#define AUX_META_METADATA_ID_OFFSET 8u
#define AUX_META_EPOCH_ID_OFFSET 12u
#define AUX_META_CAPTURE_ID_OFFSET 16u
#define AUX_META_OWNER_EPOCH_OFFSET 24u
#define AUX_META_GENERATION_OFFSET 32u
#define AUX_META_TX_TOKEN_OFFSET 40u
#define AUX_META_START_SEQ_OFFSET 48u
#define AUX_META_START_GSC_OFFSET 56u
#define AUX_META_SOURCE_EPOCH_OFFSET 64u
#define AUX_META_H_CALIBRATION_ID_OFFSET 68u
#define AUX_META_V_CALIBRATION_ID_OFFSET 72u
#define AUX_META_CONFIG_ID_OFFSET 76u
#define AUX_META_FIR_ID_OFFSET 80u
#define AUX_META_SAMPLE_COUNT_OFFSET 84u
#define AUX_META_SOURCE_ROLE_OFFSET 88u
#define AUX_META_BANK_OFFSET 89u
#define AUX_META_STATUS_OFFSET 90u
#define AUX_META_RESERVED0_OFFSET 91u
#define AUX_META_RESERVED1_OFFSET 92u
#endif
