/* Generated from contracts/event_format.json */
#ifndef CAPTURE_EVENT_H
#define CAPTURE_EVENT_H
#define EVENT_BYTES 64u
#define EVENT_CAPTURE_TAG 65537u
#define EVENT_TAG_OFFSET 0u
#define EVENT_FLAGS_OFFSET 4u
#define EVENT_PULSE_ID_OFFSET 8u
#define EVENT_OWNER_EPOCH_OFFSET 16u
#define EVENT_CONFIG_ID_OFFSET 24u
#define EVENT_TOA_GSC_OFFSET 28u
#define EVENT_WIDTH_TICKS_OFFSET 36u
#define EVENT_PEAK_POWER_OFFSET 40u
#define EVENT_ENERGY_SUM_OFFSET 44u
#define EVENT_SELECTED_RANGE_OFFSET 52u
#define EVENT_RESERVED_OFFSET 56u
#define EVENT_TOA_VALID 1u
#define EVENT_WIDTH_VALID 2u
#define EVENT_PEAK_VALID 4u
#define EVENT_ENERGY_VALID 8u
#define EVENT_SELECTED_VALID 16u
#endif
