/* Generated from contracts/fault_event_format.json */
#ifndef FAULT_EVENT_H
#define FAULT_EVENT_H
#define FAULT_EVENT_BYTES 64u
#define FAULT_EVENT_TAG 262145u
#define FAULT_EVENT_TAG_OFFSET 0u
#define FAULT_EVENT_FLAGS_OFFSET 4u
#define FAULT_EVENT_OCCURRENCES_OFFSET 8u
#define FAULT_EVENT_RESERVED_HEADER_OFFSET 12u
#define FAULT_EVENT_SNAPSHOT_TAG_OFFSET 16u
#define FAULT_EVENT_SNAPSHOT_FLAGS_OFFSET 20u
#define FAULT_EVENT_CONFIG_ID_OFFSET 24u
#define FAULT_EVENT_RF_STATE_OFFSET 28u
#define FAULT_EVENT_NORMALIZED_INPUTS_OFFSET 32u
#define FAULT_EVENT_LOGICAL_OUTPUTS_OFFSET 36u
#define FAULT_EVENT_OBSERVATION_GSC_OFFSET 40u
#define FAULT_EVENT_RESERVED_TAIL_OFFSET 48u
#define FAULT_EVENT_COUNT_SATURATED 1u
#endif
