/* Generated from contracts/replay_identity_event.json */
#ifndef REPLAY_IDENTITY_H
#define REPLAY_IDENTITY_H
#define REPLAY_IDENTITY_BYTES 64u
#define REPLAY_IDENTITY_TAG 393217u
#define REPLAY_IDENTITY_TAG_OFFSET 0u
#define REPLAY_IDENTITY_RESERVED_OFFSET 4u
#define REPLAY_IDENTITY_TOKEN_OFFSET 8u
#define REPLAY_IDENTITY_TASK_ID_OFFSET 16u
#define REPLAY_IDENTITY_PULSE_ID_OFFSET 24u
#define REPLAY_IDENTITY_OWNER_EPOCH_OFFSET 32u
#define REPLAY_IDENTITY_GENERATION_OFFSET 40u
#define REPLAY_IDENTITY_CONFIG_ID_OFFSET 48u
#define REPLAY_IDENTITY_FIR_ID_OFFSET 52u
#define REPLAY_IDENTITY_SOURCE_EPOCH_OFFSET 56u
#define REPLAY_IDENTITY_GROUP_OFFSET 60u
#define REPLAY_IDENTITY_BANK_OFFSET 62u
#endif
