/* Generated from contracts/tx_lifecycle_event.json */
#ifndef TX_LIFECYCLE_H
#define TX_LIFECYCLE_H
#define TX_LIFECYCLE_BYTES 64u
#define TX_LIFECYCLE_TAG 327681u
#define TX_LIFECYCLE_TAG_OFFSET 0u
#define TX_LIFECYCLE_FLAGS_OFFSET 4u
#define TX_LIFECYCLE_SOURCE_OFFSET 8u
#define TX_LIFECYCLE_REASON_OFFSET 12u
#define TX_LIFECYCLE_COMMAND_SEQUENCE_OFFSET 16u
#define TX_LIFECYCLE_CONFIG_ID_OFFSET 20u
#define TX_LIFECYCLE_TOKEN_OFFSET 24u
#define TX_LIFECYCLE_ACCEPT_GSC_OFFSET 32u
#define TX_LIFECYCLE_DRAIN_GSC_OFFSET 40u
#define TX_LIFECYCLE_RETIRE_GSC_OFFSET 48u
#define TX_LIFECYCLE_RESERVED_OFFSET 56u
#define TX_LIFECYCLE_DIGITAL_DRAINED 1u
#define TX_LIFECYCLE_TIME_VALID 2u
#define TX_LIFECYCLE_SINK_CONFIRMED 4u
#define TX_LIFECYCLE_SOURCE_DDS 1u
#define TX_LIFECYCLE_SOURCE_AWG 2u
#define TX_LIFECYCLE_SOURCE_REPLAY 3u
#define TX_LIFECYCLE_REASON_NORMAL 0u
#define TX_LIFECYCLE_REASON_STOP 1u
#define TX_LIFECYCLE_REASON_SAFETY 2u
#define TX_LIFECYCLE_REASON_MUTE 3u
#define TX_LIFECYCLE_REASON_REPLAY_ABORT 4u
#endif
