// Generated by tools/generate_fir_rtl.py; do not hand edit.
// Coefficient JSON SHA256 8523fcf1018f481f2ea01615446bc633dd570d2a60e78a198afa341b22405597
// Two independent real histories implement one complex physical path.
// out_sat[0]=first stage, out_sat[1]=second stage, OR across lanes and I/Q.
module fir_tx_lane(input wire clk,rst,in_valid,
 input wire [15:0] in_i,in_q, output wire out_valid,
 output wire [63:0] out_i,out_q, output wire [1:0] out_sat);
 wire [47:0] mid_i,mid_q; wire mid_valid,unused_mid_valid,unused_out_valid;
 wire [1:0] sat1i,sat1q; wire [3:0] sat2i,sat2q;
 fir_tx_fir75 fi(.clk(clk),.rst(rst),.in_valid(in_valid),.in_data(in_i),.out_valid(mid_valid),.out_data(mid_i),.out_sat(sat1i));
 fir_tx_fir75 fq(.clk(clk),.rst(rst),.in_valid(in_valid),.in_data(in_q),.out_valid(unused_mid_valid),.out_data(mid_q),.out_sat(sat1q));
 fir_tx_hb19 si(.clk(clk),.rst(rst),.in_valid(mid_valid),.in_data(mid_i),.out_valid(out_valid),.out_data(out_i),.out_sat(sat2i));
 fir_tx_hb19 sq(.clk(clk),.rst(rst),.in_valid(mid_valid),.in_data(mid_q),.out_valid(unused_out_valid),.out_data(out_q),.out_sat(sat2q));
 reg [5:0] sat1_delay;
 always @(posedge clk) if(rst) sat1_delay<=0;
 else sat1_delay <= {sat1_delay[4:0],(|sat1i)|(|sat1q)};
 assign out_sat={(|sat2i)|(|sat2q),sat1_delay[5]};
endmodule
