// Generated by tools/generate_fir_rtl.py; do not hand edit.
// Coefficient JSON SHA256 8523fcf1018f481f2ea01615446bc633dd570d2a60e78a198afa341b22405597
// Lane 0 is earliest. Valid gaps preserve sample history; reset clears history/valid.
// TX_FIR75_L2: source COE SHA256 1e0572249ab3ccd15a45362bdefbf8ec3d658433ae37df58d3a7c366f296479b
// Pipeline: registered preadd, multiply, 5 balanced sum levels, round/saturate.
// 8 registers; accepted edge n -> output edge n+7; II=1.
module fir_tx_fir75(input wire clk,rst,in_valid,
 input wire [15:0] in_data, output wire out_valid,
 output reg [47:0] out_data, output reg [1:0] out_sat);
 reg signed [15:0] history[0:37];
 reg [7:0] valid_pipe;
 integer h;
 always @(posedge clk) begin
   if(rst) begin
     valid_pipe <= 0;
     for(h=0;h<38;h=h+1) history[h]<=0;
   end else begin
     valid_pipe <= {valid_pipe[6:0],in_valid};
     if(in_valid) begin
       history[0] <= in_data[0 +: 16];
       history[1] <= history[0];
       history[2] <= history[1];
       history[3] <= history[2];
       history[4] <= history[3];
       history[5] <= history[4];
       history[6] <= history[5];
       history[7] <= history[6];
       history[8] <= history[7];
       history[9] <= history[8];
       history[10] <= history[9];
       history[11] <= history[10];
       history[12] <= history[11];
       history[13] <= history[12];
       history[14] <= history[13];
       history[15] <= history[14];
       history[16] <= history[15];
       history[17] <= history[16];
       history[18] <= history[17];
       history[19] <= history[18];
       history[20] <= history[19];
       history[21] <= history[20];
       history[22] <= history[21];
       history[23] <= history[22];
       history[24] <= history[23];
       history[25] <= history[24];
       history[26] <= history[25];
       history[27] <= history[26];
       history[28] <= history[27];
       history[29] <= history[28];
       history[30] <= history[29];
       history[31] <= history[30];
       history[32] <= history[31];
       history[33] <= history[32];
       history[34] <= history[33];
       history[35] <= history[34];
       history[36] <= history[35];
       history[37] <= history[36];
     end
   end
 end
 assign out_valid=valid_pipe[7];
 wire signed [15:0] a0_0 = $signed(in_data[0 +: 16]);
 wire signed [15:0] b0_0 = history[36];
 reg signed [16:0] pre0_0;
 (* use_dsp="yes" *) reg signed [47:0] prod0_0;
 always @(posedge clk) begin
   pre0_0 <= $signed({a0_0[15],a0_0}) + $signed({b0_0[15],b0_0});
   prod0_0 <= pre0_0 * 18'sd13;
 end
 wire signed [15:0] a0_1 = history[0];
 wire signed [15:0] b0_1 = history[35];
 reg signed [16:0] pre0_1;
 (* use_dsp="yes" *) reg signed [47:0] prod0_1;
 always @(posedge clk) begin
   pre0_1 <= $signed({a0_1[15],a0_1}) + $signed({b0_1[15],b0_1});
   prod0_1 <= pre0_1 * -18'sd88;
 end
 wire signed [15:0] a0_2 = history[1];
 wire signed [15:0] b0_2 = history[34];
 reg signed [16:0] pre0_2;
 (* use_dsp="yes" *) reg signed [47:0] prod0_2;
 always @(posedge clk) begin
   pre0_2 <= $signed({a0_2[15],a0_2}) + $signed({b0_2[15],b0_2});
   prod0_2 <= pre0_2 * 18'sd95;
 end
 wire signed [15:0] a0_3 = history[2];
 wire signed [15:0] b0_3 = history[33];
 reg signed [16:0] pre0_3;
 (* use_dsp="yes" *) reg signed [47:0] prod0_3;
 always @(posedge clk) begin
   pre0_3 <= $signed({a0_3[15],a0_3}) + $signed({b0_3[15],b0_3});
   prod0_3 <= pre0_3 * -18'sd107;
 end
 wire signed [15:0] a0_4 = history[3];
 wire signed [15:0] b0_4 = history[32];
 reg signed [16:0] pre0_4;
 (* use_dsp="yes" *) reg signed [47:0] prod0_4;
 always @(posedge clk) begin
   pre0_4 <= $signed({a0_4[15],a0_4}) + $signed({b0_4[15],b0_4});
   prod0_4 <= pre0_4 * 18'sd78;
 end
 wire signed [15:0] a0_5 = history[4];
 wire signed [15:0] b0_5 = history[31];
 reg signed [16:0] pre0_5;
 (* use_dsp="yes" *) reg signed [47:0] prod0_5;
 always @(posedge clk) begin
   pre0_5 <= $signed({a0_5[15],a0_5}) + $signed({b0_5[15],b0_5});
   prod0_5 <= pre0_5 * 18'sd15;
 end
 wire signed [15:0] a0_6 = history[5];
 wire signed [15:0] b0_6 = history[30];
 reg signed [16:0] pre0_6;
 (* use_dsp="yes" *) reg signed [47:0] prod0_6;
 always @(posedge clk) begin
   pre0_6 <= $signed({a0_6[15],a0_6}) + $signed({b0_6[15],b0_6});
   prod0_6 <= pre0_6 * -18'sd186;
 end
 wire signed [15:0] a0_7 = history[6];
 wire signed [15:0] b0_7 = history[29];
 reg signed [16:0] pre0_7;
 (* use_dsp="yes" *) reg signed [47:0] prod0_7;
 always @(posedge clk) begin
   pre0_7 <= $signed({a0_7[15],a0_7}) + $signed({b0_7[15],b0_7});
   prod0_7 <= pre0_7 * 18'sd439;
 end
 wire signed [15:0] a0_8 = history[7];
 wire signed [15:0] b0_8 = history[28];
 reg signed [16:0] pre0_8;
 (* use_dsp="yes" *) reg signed [47:0] prod0_8;
 always @(posedge clk) begin
   pre0_8 <= $signed({a0_8[15],a0_8}) + $signed({b0_8[15],b0_8});
   prod0_8 <= pre0_8 * -18'sd757;
 end
 wire signed [15:0] a0_9 = history[8];
 wire signed [15:0] b0_9 = history[27];
 reg signed [16:0] pre0_9;
 (* use_dsp="yes" *) reg signed [47:0] prod0_9;
 always @(posedge clk) begin
   pre0_9 <= $signed({a0_9[15],a0_9}) + $signed({b0_9[15],b0_9});
   prod0_9 <= pre0_9 * 18'sd1094;
 end
 wire signed [15:0] a0_10 = history[9];
 wire signed [15:0] b0_10 = history[26];
 reg signed [16:0] pre0_10;
 (* use_dsp="yes" *) reg signed [47:0] prod0_10;
 always @(posedge clk) begin
   pre0_10 <= $signed({a0_10[15],a0_10}) + $signed({b0_10[15],b0_10});
   prod0_10 <= pre0_10 * -18'sd1383;
 end
 wire signed [15:0] a0_11 = history[10];
 wire signed [15:0] b0_11 = history[25];
 reg signed [16:0] pre0_11;
 (* use_dsp="yes" *) reg signed [47:0] prod0_11;
 always @(posedge clk) begin
   pre0_11 <= $signed({a0_11[15],a0_11}) + $signed({b0_11[15],b0_11});
   prod0_11 <= pre0_11 * 18'sd1527;
 end
 wire signed [15:0] a0_12 = history[11];
 wire signed [15:0] b0_12 = history[24];
 reg signed [16:0] pre0_12;
 (* use_dsp="yes" *) reg signed [47:0] prod0_12;
 always @(posedge clk) begin
   pre0_12 <= $signed({a0_12[15],a0_12}) + $signed({b0_12[15],b0_12});
   prod0_12 <= pre0_12 * -18'sd1413;
 end
 wire signed [15:0] a0_13 = history[12];
 wire signed [15:0] b0_13 = history[23];
 reg signed [16:0] pre0_13;
 (* use_dsp="yes" *) reg signed [47:0] prod0_13;
 always @(posedge clk) begin
   pre0_13 <= $signed({a0_13[15],a0_13}) + $signed({b0_13[15],b0_13});
   prod0_13 <= pre0_13 * 18'sd906;
 end
 wire signed [15:0] a0_14 = history[13];
 wire signed [15:0] b0_14 = history[22];
 reg signed [16:0] pre0_14;
 (* use_dsp="yes" *) reg signed [47:0] prod0_14;
 always @(posedge clk) begin
   pre0_14 <= $signed({a0_14[15],a0_14}) + $signed({b0_14[15],b0_14});
   prod0_14 <= pre0_14 * 18'sd156;
 end
 wire signed [15:0] a0_15 = history[14];
 wire signed [15:0] b0_15 = history[21];
 reg signed [16:0] pre0_15;
 (* use_dsp="yes" *) reg signed [47:0] prod0_15;
 always @(posedge clk) begin
   pre0_15 <= $signed({a0_15[15],a0_15}) + $signed({b0_15[15],b0_15});
   prod0_15 <= pre0_15 * -18'sd2024;
 end
 wire signed [15:0] a0_16 = history[15];
 wire signed [15:0] b0_16 = history[20];
 reg signed [16:0] pre0_16;
 (* use_dsp="yes" *) reg signed [47:0] prod0_16;
 always @(posedge clk) begin
   pre0_16 <= $signed({a0_16[15],a0_16}) + $signed({b0_16[15],b0_16});
   prod0_16 <= pre0_16 * 18'sd5268;
 end
 wire signed [15:0] a0_17 = history[16];
 wire signed [15:0] b0_17 = history[19];
 reg signed [16:0] pre0_17;
 (* use_dsp="yes" *) reg signed [47:0] prod0_17;
 always @(posedge clk) begin
   pre0_17 <= $signed({a0_17[15],a0_17}) + $signed({b0_17[15],b0_17});
   prod0_17 <= pre0_17 * -18'sd11956;
 end
 wire signed [15:0] a0_18 = history[17];
 wire signed [15:0] b0_18 = history[18];
 reg signed [16:0] pre0_18;
 (* use_dsp="yes" *) reg signed [47:0] prod0_18;
 always @(posedge clk) begin
   pre0_18 <= $signed({a0_18[15],a0_18}) + $signed({b0_18[15],b0_18});
   prod0_18 <= pre0_18 * 18'sd41098;
 end
 reg signed [47:0] sum0_0_0;
 always @(posedge clk) sum0_0_0 <= prod0_0 + prod0_1;
 reg signed [47:0] sum0_0_1;
 always @(posedge clk) sum0_0_1 <= prod0_2 + prod0_3;
 reg signed [47:0] sum0_0_2;
 always @(posedge clk) sum0_0_2 <= prod0_4 + prod0_5;
 reg signed [47:0] sum0_0_3;
 always @(posedge clk) sum0_0_3 <= prod0_6 + prod0_7;
 reg signed [47:0] sum0_0_4;
 always @(posedge clk) sum0_0_4 <= prod0_8 + prod0_9;
 reg signed [47:0] sum0_0_5;
 always @(posedge clk) sum0_0_5 <= prod0_10 + prod0_11;
 reg signed [47:0] sum0_0_6;
 always @(posedge clk) sum0_0_6 <= prod0_12 + prod0_13;
 reg signed [47:0] sum0_0_7;
 always @(posedge clk) sum0_0_7 <= prod0_14 + prod0_15;
 reg signed [47:0] sum0_0_8;
 always @(posedge clk) sum0_0_8 <= prod0_16 + prod0_17;
 reg signed [47:0] sum0_0_9;
 always @(posedge clk) sum0_0_9 <= prod0_18 + 48'sd0;
 reg signed [47:0] sum0_0_10;
 always @(posedge clk) sum0_0_10 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_11;
 always @(posedge clk) sum0_0_11 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_12;
 always @(posedge clk) sum0_0_12 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_13;
 always @(posedge clk) sum0_0_13 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_14;
 always @(posedge clk) sum0_0_14 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_0_15;
 always @(posedge clk) sum0_0_15 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_1_0;
 always @(posedge clk) sum0_1_0 <= sum0_0_0 + sum0_0_1;
 reg signed [47:0] sum0_1_1;
 always @(posedge clk) sum0_1_1 <= sum0_0_2 + sum0_0_3;
 reg signed [47:0] sum0_1_2;
 always @(posedge clk) sum0_1_2 <= sum0_0_4 + sum0_0_5;
 reg signed [47:0] sum0_1_3;
 always @(posedge clk) sum0_1_3 <= sum0_0_6 + sum0_0_7;
 reg signed [47:0] sum0_1_4;
 always @(posedge clk) sum0_1_4 <= sum0_0_8 + sum0_0_9;
 reg signed [47:0] sum0_1_5;
 always @(posedge clk) sum0_1_5 <= sum0_0_10 + sum0_0_11;
 reg signed [47:0] sum0_1_6;
 always @(posedge clk) sum0_1_6 <= sum0_0_12 + sum0_0_13;
 reg signed [47:0] sum0_1_7;
 always @(posedge clk) sum0_1_7 <= sum0_0_14 + sum0_0_15;
 reg signed [47:0] sum0_2_0;
 always @(posedge clk) sum0_2_0 <= sum0_1_0 + sum0_1_1;
 reg signed [47:0] sum0_2_1;
 always @(posedge clk) sum0_2_1 <= sum0_1_2 + sum0_1_3;
 reg signed [47:0] sum0_2_2;
 always @(posedge clk) sum0_2_2 <= sum0_1_4 + sum0_1_5;
 reg signed [47:0] sum0_2_3;
 always @(posedge clk) sum0_2_3 <= sum0_1_6 + sum0_1_7;
 reg signed [47:0] sum0_3_0;
 always @(posedge clk) sum0_3_0 <= sum0_2_0 + sum0_2_1;
 reg signed [47:0] sum0_3_1;
 always @(posedge clk) sum0_3_1 <= sum0_2_2 + sum0_2_3;
 reg signed [47:0] sum0_4_0;
 always @(posedge clk) sum0_4_0 <= sum0_3_0 + sum0_3_1;
 wire signed [23:0] q0; wire sat0;
 fir_quantize #(.SHIFT(10),.BITS(24)) qnt0(.value(sum0_4_0),.result(q0),.sat(sat0));
 always @(posedge clk) begin
   if(rst) begin out_data[0 +: 24]<=0; out_sat[0]<=0; end
   else begin out_data[0 +: 24]<=q0; out_sat[0]<=sat0; end
 end
 wire signed [15:0] a1_0 = $signed(in_data[0 +: 16]);
 wire signed [15:0] b1_0 = history[35];
 reg signed [16:0] pre1_0;
 (* use_dsp="yes" *) reg signed [47:0] prod1_0;
 always @(posedge clk) begin
   pre1_0 <= $signed({a1_0[15],a1_0}) + $signed({b1_0[15],b1_0});
   prod1_0 <= pre1_0 * -18'sd40;
 end
 wire signed [15:0] a1_1 = history[0];
 wire signed [15:0] b1_1 = history[34];
 reg signed [16:0] pre1_1;
 (* use_dsp="yes" *) reg signed [47:0] prod1_1;
 always @(posedge clk) begin
   pre1_1 <= $signed({a1_1[15],a1_1}) + $signed({b1_1[15],b1_1});
   prod1_1 <= pre1_1 * -18'sd32;
 end
 wire signed [15:0] a1_2 = history[1];
 wire signed [15:0] b1_2 = history[33];
 reg signed [16:0] pre1_2;
 (* use_dsp="yes" *) reg signed [47:0] prod1_2;
 always @(posedge clk) begin
   pre1_2 <= $signed({a1_2[15],a1_2}) + $signed({b1_2[15],b1_2});
   prod1_2 <= pre1_2 * 18'sd85;
 end
 wire signed [15:0] a1_3 = history[2];
 wire signed [15:0] b1_3 = history[32];
 reg signed [16:0] pre1_3;
 (* use_dsp="yes" *) reg signed [47:0] prod1_3;
 always @(posedge clk) begin
   pre1_3 <= $signed({a1_3[15],a1_3}) + $signed({b1_3[15],b1_3});
   prod1_3 <= pre1_3 * -18'sd177;
 end
 wire signed [15:0] a1_4 = history[3];
 wire signed [15:0] b1_4 = history[31];
 reg signed [16:0] pre1_4;
 (* use_dsp="yes" *) reg signed [47:0] prod1_4;
 always @(posedge clk) begin
   pre1_4 <= $signed({a1_4[15],a1_4}) + $signed({b1_4[15],b1_4});
   prod1_4 <= pre1_4 * 18'sd288;
 end
 wire signed [15:0] a1_5 = history[4];
 wire signed [15:0] b1_5 = history[30];
 reg signed [16:0] pre1_5;
 (* use_dsp="yes" *) reg signed [47:0] prod1_5;
 always @(posedge clk) begin
   pre1_5 <= $signed({a1_5[15],a1_5}) + $signed({b1_5[15],b1_5});
   prod1_5 <= pre1_5 * -18'sd396;
 end
 wire signed [15:0] a1_6 = history[5];
 wire signed [15:0] b1_6 = history[29];
 reg signed [16:0] pre1_6;
 (* use_dsp="yes" *) reg signed [47:0] prod1_6;
 always @(posedge clk) begin
   pre1_6 <= $signed({a1_6[15],a1_6}) + $signed({b1_6[15],b1_6});
   prod1_6 <= pre1_6 * 18'sd461;
 end
 wire signed [15:0] a1_7 = history[6];
 wire signed [15:0] b1_7 = history[28];
 reg signed [16:0] pre1_7;
 (* use_dsp="yes" *) reg signed [47:0] prod1_7;
 always @(posedge clk) begin
   pre1_7 <= $signed({a1_7[15],a1_7}) + $signed({b1_7[15],b1_7});
   prod1_7 <= pre1_7 * -18'sd437;
 end
 wire signed [15:0] a1_8 = history[7];
 wire signed [15:0] b1_8 = history[27];
 reg signed [16:0] pre1_8;
 (* use_dsp="yes" *) reg signed [47:0] prod1_8;
 always @(posedge clk) begin
   pre1_8 <= $signed({a1_8[15],a1_8}) + $signed({b1_8[15],b1_8});
   prod1_8 <= pre1_8 * 18'sd272;
 end
 wire signed [15:0] a1_9 = history[8];
 wire signed [15:0] b1_9 = history[26];
 reg signed [16:0] pre1_9;
 (* use_dsp="yes" *) reg signed [47:0] prod1_9;
 always @(posedge clk) begin
   pre1_9 <= $signed({a1_9[15],a1_9}) + $signed({b1_9[15],b1_9});
   prod1_9 <= pre1_9 * 18'sd79;
 end
 wire signed [15:0] a1_10 = history[9];
 wire signed [15:0] b1_10 = history[25];
 reg signed [16:0] pre1_10;
 (* use_dsp="yes" *) reg signed [47:0] prod1_10;
 always @(posedge clk) begin
   pre1_10 <= $signed({a1_10[15],a1_10}) + $signed({b1_10[15],b1_10});
   prod1_10 <= pre1_10 * -18'sd641;
 end
 wire signed [15:0] a1_11 = history[10];
 wire signed [15:0] b1_11 = history[24];
 reg signed [16:0] pre1_11;
 (* use_dsp="yes" *) reg signed [47:0] prod1_11;
 always @(posedge clk) begin
   pre1_11 <= $signed({a1_11[15],a1_11}) + $signed({b1_11[15],b1_11});
   prod1_11 <= pre1_11 * 18'sd1417;
 end
 wire signed [15:0] a1_12 = history[11];
 wire signed [15:0] b1_12 = history[23];
 reg signed [16:0] pre1_12;
 (* use_dsp="yes" *) reg signed [47:0] prod1_12;
 always @(posedge clk) begin
   pre1_12 <= $signed({a1_12[15],a1_12}) + $signed({b1_12[15],b1_12});
   prod1_12 <= pre1_12 * -18'sd2373;
 end
 wire signed [15:0] a1_13 = history[12];
 wire signed [15:0] b1_13 = history[22];
 reg signed [16:0] pre1_13;
 (* use_dsp="yes" *) reg signed [47:0] prod1_13;
 always @(posedge clk) begin
   pre1_13 <= $signed({a1_13[15],a1_13}) + $signed({b1_13[15],b1_13});
   prod1_13 <= pre1_13 * 18'sd3446;
 end
 wire signed [15:0] a1_14 = history[13];
 wire signed [15:0] b1_14 = history[21];
 reg signed [16:0] pre1_14;
 (* use_dsp="yes" *) reg signed [47:0] prod1_14;
 always @(posedge clk) begin
   pre1_14 <= $signed({a1_14[15],a1_14}) + $signed({b1_14[15],b1_14});
   prod1_14 <= pre1_14 * -18'sd4544;
 end
 wire signed [15:0] a1_15 = history[14];
 wire signed [15:0] b1_15 = history[20];
 reg signed [16:0] pre1_15;
 (* use_dsp="yes" *) reg signed [47:0] prod1_15;
 always @(posedge clk) begin
   pre1_15 <= $signed({a1_15[15],a1_15}) + $signed({b1_15[15],b1_15});
   prod1_15 <= pre1_15 * 18'sd5558;
 end
 wire signed [15:0] a1_16 = history[15];
 wire signed [15:0] b1_16 = history[19];
 reg signed [16:0] pre1_16;
 (* use_dsp="yes" *) reg signed [47:0] prod1_16;
 always @(posedge clk) begin
   pre1_16 <= $signed({a1_16[15],a1_16}) + $signed({b1_16[15],b1_16});
   prod1_16 <= pre1_16 * -18'sd6380;
 end
 wire signed [15:0] a1_17 = history[16];
 wire signed [15:0] b1_17 = history[18];
 reg signed [16:0] pre1_17;
 (* use_dsp="yes" *) reg signed [47:0] prod1_17;
 always @(posedge clk) begin
   pre1_17 <= $signed({a1_17[15],a1_17}) + $signed({b1_17[15],b1_17});
   prod1_17 <= pre1_17 * 18'sd6915;
 end
 wire signed [15:0] a1_18 = history[17];
 wire signed [15:0] b1_18 = 0;
 reg signed [16:0] pre1_18;
 (* use_dsp="yes" *) reg signed [47:0] prod1_18;
 always @(posedge clk) begin
   pre1_18 <= $signed({a1_18[15],a1_18}) + $signed({b1_18[15],b1_18});
   prod1_18 <= pre1_18 * 18'sd58518;
 end
 reg signed [47:0] sum1_0_0;
 always @(posedge clk) sum1_0_0 <= prod1_0 + prod1_1;
 reg signed [47:0] sum1_0_1;
 always @(posedge clk) sum1_0_1 <= prod1_2 + prod1_3;
 reg signed [47:0] sum1_0_2;
 always @(posedge clk) sum1_0_2 <= prod1_4 + prod1_5;
 reg signed [47:0] sum1_0_3;
 always @(posedge clk) sum1_0_3 <= prod1_6 + prod1_7;
 reg signed [47:0] sum1_0_4;
 always @(posedge clk) sum1_0_4 <= prod1_8 + prod1_9;
 reg signed [47:0] sum1_0_5;
 always @(posedge clk) sum1_0_5 <= prod1_10 + prod1_11;
 reg signed [47:0] sum1_0_6;
 always @(posedge clk) sum1_0_6 <= prod1_12 + prod1_13;
 reg signed [47:0] sum1_0_7;
 always @(posedge clk) sum1_0_7 <= prod1_14 + prod1_15;
 reg signed [47:0] sum1_0_8;
 always @(posedge clk) sum1_0_8 <= prod1_16 + prod1_17;
 reg signed [47:0] sum1_0_9;
 always @(posedge clk) sum1_0_9 <= prod1_18 + 48'sd0;
 reg signed [47:0] sum1_0_10;
 always @(posedge clk) sum1_0_10 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum1_0_11;
 always @(posedge clk) sum1_0_11 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum1_0_12;
 always @(posedge clk) sum1_0_12 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum1_0_13;
 always @(posedge clk) sum1_0_13 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum1_0_14;
 always @(posedge clk) sum1_0_14 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum1_0_15;
 always @(posedge clk) sum1_0_15 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum1_1_0;
 always @(posedge clk) sum1_1_0 <= sum1_0_0 + sum1_0_1;
 reg signed [47:0] sum1_1_1;
 always @(posedge clk) sum1_1_1 <= sum1_0_2 + sum1_0_3;
 reg signed [47:0] sum1_1_2;
 always @(posedge clk) sum1_1_2 <= sum1_0_4 + sum1_0_5;
 reg signed [47:0] sum1_1_3;
 always @(posedge clk) sum1_1_3 <= sum1_0_6 + sum1_0_7;
 reg signed [47:0] sum1_1_4;
 always @(posedge clk) sum1_1_4 <= sum1_0_8 + sum1_0_9;
 reg signed [47:0] sum1_1_5;
 always @(posedge clk) sum1_1_5 <= sum1_0_10 + sum1_0_11;
 reg signed [47:0] sum1_1_6;
 always @(posedge clk) sum1_1_6 <= sum1_0_12 + sum1_0_13;
 reg signed [47:0] sum1_1_7;
 always @(posedge clk) sum1_1_7 <= sum1_0_14 + sum1_0_15;
 reg signed [47:0] sum1_2_0;
 always @(posedge clk) sum1_2_0 <= sum1_1_0 + sum1_1_1;
 reg signed [47:0] sum1_2_1;
 always @(posedge clk) sum1_2_1 <= sum1_1_2 + sum1_1_3;
 reg signed [47:0] sum1_2_2;
 always @(posedge clk) sum1_2_2 <= sum1_1_4 + sum1_1_5;
 reg signed [47:0] sum1_2_3;
 always @(posedge clk) sum1_2_3 <= sum1_1_6 + sum1_1_7;
 reg signed [47:0] sum1_3_0;
 always @(posedge clk) sum1_3_0 <= sum1_2_0 + sum1_2_1;
 reg signed [47:0] sum1_3_1;
 always @(posedge clk) sum1_3_1 <= sum1_2_2 + sum1_2_3;
 reg signed [47:0] sum1_4_0;
 always @(posedge clk) sum1_4_0 <= sum1_3_0 + sum1_3_1;
 wire signed [23:0] q1; wire sat1;
 fir_quantize #(.SHIFT(10),.BITS(24)) qnt1(.value(sum1_4_0),.result(q1),.sat(sat1));
 always @(posedge clk) begin
   if(rst) begin out_data[24 +: 24]<=0; out_sat[1]<=0; end
   else begin out_data[24 +: 24]<=q1; out_sat[1]<=sat1; end
 end
endmodule
