// Generated by tools/generate_fir_rtl.py; do not hand edit.
// Coefficient JSON SHA256 8523fcf1018f481f2ea01615446bc633dd570d2a60e78a198afa341b22405597
// Lane 0 is earliest. Valid gaps preserve sample history; reset clears history/valid.
// TX_HB19_L2: source COE SHA256 3f93b09545f2a54cac4aef674bff483c5a49d731519834daa3a633d67a366221
// Pipeline: registered preadd, multiply, 3 balanced sum levels, round/saturate.
// 6 registers; accepted edge n -> output edge n+5; II=1.
module fir_tx_hb19(input wire clk,rst,in_valid,
 input wire [47:0] in_data, output wire out_valid,
 output reg [63:0] out_data, output reg [3:0] out_sat);
 reg signed [23:0] history[0:9];
 reg [5:0] valid_pipe;
 integer h;
 always @(posedge clk) begin
   if(rst) begin
     valid_pipe <= 0;
     for(h=0;h<10;h=h+1) history[h]<=0;
   end else begin
     valid_pipe <= {valid_pipe[4:0],in_valid};
     if(in_valid) begin
       history[0] <= in_data[24 +: 24];
       history[1] <= in_data[0 +: 24];
       history[2] <= history[0];
       history[3] <= history[1];
       history[4] <= history[2];
       history[5] <= history[3];
       history[6] <= history[4];
       history[7] <= history[5];
       history[8] <= history[6];
       history[9] <= history[7];
     end
   end
 end
 assign out_valid=valid_pipe[5];
 wire signed [23:0] a0_0 = $signed(in_data[0 +: 24]);
 wire signed [23:0] b0_0 = history[8];
 reg signed [24:0] pre0_0;
 (* use_dsp="yes" *) reg signed [47:0] prod0_0;
 always @(posedge clk) begin
   pre0_0 <= $signed({a0_0[23],a0_0}) + $signed({b0_0[23],b0_0});
   prod0_0 <= pre0_0 * 18'sd147;
 end
 wire signed [23:0] a0_1 = history[0];
 wire signed [23:0] b0_1 = history[7];
 reg signed [24:0] pre0_1;
 (* use_dsp="yes" *) reg signed [47:0] prod0_1;
 always @(posedge clk) begin
   pre0_1 <= $signed({a0_1[23],a0_1}) + $signed({b0_1[23],b0_1});
   prod0_1 <= pre0_1 * -18'sd932;
 end
 wire signed [23:0] a0_2 = history[1];
 wire signed [23:0] b0_2 = history[6];
 reg signed [24:0] pre0_2;
 (* use_dsp="yes" *) reg signed [47:0] prod0_2;
 always @(posedge clk) begin
   pre0_2 <= $signed({a0_2[23],a0_2}) + $signed({b0_2[23],b0_2});
   prod0_2 <= pre0_2 * 18'sd3434;
 end
 wire signed [23:0] a0_3 = history[2];
 wire signed [23:0] b0_3 = history[5];
 reg signed [24:0] pre0_3;
 (* use_dsp="yes" *) reg signed [47:0] prod0_3;
 always @(posedge clk) begin
   pre0_3 <= $signed({a0_3[23],a0_3}) + $signed({b0_3[23],b0_3});
   prod0_3 <= pre0_3 * -18'sd10218;
 end
 wire signed [23:0] a0_4 = history[3];
 wire signed [23:0] b0_4 = history[4];
 reg signed [24:0] pre0_4;
 (* use_dsp="yes" *) reg signed [47:0] prod0_4;
 always @(posedge clk) begin
   pre0_4 <= $signed({a0_4[23],a0_4}) + $signed({b0_4[23],b0_4});
   prod0_4 <= pre0_4 * 18'sd40339;
 end
 reg signed [47:0] sum0_0_0;
 always @(posedge clk) sum0_0_0 <= prod0_0 + prod0_1;
 reg signed [47:0] sum0_0_1;
 always @(posedge clk) sum0_0_1 <= prod0_2 + prod0_3;
 reg signed [47:0] sum0_0_2;
 always @(posedge clk) sum0_0_2 <= prod0_4 + 48'sd0;
 reg signed [47:0] sum0_0_3;
 always @(posedge clk) sum0_0_3 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum0_1_0;
 always @(posedge clk) sum0_1_0 <= sum0_0_0 + sum0_0_1;
 reg signed [47:0] sum0_1_1;
 always @(posedge clk) sum0_1_1 <= sum0_0_2 + sum0_0_3;
 reg signed [47:0] sum0_2_0;
 always @(posedge clk) sum0_2_0 <= sum0_1_0 + sum0_1_1;
 wire signed [15:0] q0; wire sat0;
 fir_quantize #(.SHIFT(22),.BITS(16)) qnt0(.value(sum0_2_0),.result(q0),.sat(sat0));
 always @(posedge clk) begin
   if(rst) begin out_data[0 +: 16]<=0; out_sat[0]<=0; end
   else begin out_data[0 +: 16]<=q0; out_sat[0]<=sat0; end
 end
 wire signed [23:0] a1_0 = history[3];
 wire signed [23:0] b1_0 = 0;
 reg signed [24:0] pre1_0;
 (* use_dsp="yes" *) reg signed [47:0] prod1_0;
 always @(posedge clk) begin
   pre1_0 <= $signed({a1_0[23],a1_0}) + $signed({b1_0[23],b1_0});
   prod1_0 <= pre1_0 * 18'sd65536;
 end
 reg signed [47:0] sum1_0_0;
 always @(posedge clk) sum1_0_0 <= prod1_0 + 48'sd0;
 reg signed [47:0] sum1_0_1;
 always @(posedge clk) sum1_0_1 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum1_0_2;
 always @(posedge clk) sum1_0_2 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum1_0_3;
 always @(posedge clk) sum1_0_3 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum1_1_0;
 always @(posedge clk) sum1_1_0 <= sum1_0_0 + sum1_0_1;
 reg signed [47:0] sum1_1_1;
 always @(posedge clk) sum1_1_1 <= sum1_0_2 + sum1_0_3;
 reg signed [47:0] sum1_2_0;
 always @(posedge clk) sum1_2_0 <= sum1_1_0 + sum1_1_1;
 wire signed [15:0] q1; wire sat1;
 fir_quantize #(.SHIFT(22),.BITS(16)) qnt1(.value(sum1_2_0),.result(q1),.sat(sat1));
 always @(posedge clk) begin
   if(rst) begin out_data[16 +: 16]<=0; out_sat[1]<=0; end
   else begin out_data[16 +: 16]<=q1; out_sat[1]<=sat1; end
 end
 wire signed [23:0] a2_0 = $signed(in_data[24 +: 24]);
 wire signed [23:0] b2_0 = history[7];
 reg signed [24:0] pre2_0;
 (* use_dsp="yes" *) reg signed [47:0] prod2_0;
 always @(posedge clk) begin
   pre2_0 <= $signed({a2_0[23],a2_0}) + $signed({b2_0[23],b2_0});
   prod2_0 <= pre2_0 * 18'sd147;
 end
 wire signed [23:0] a2_1 = $signed(in_data[0 +: 24]);
 wire signed [23:0] b2_1 = history[6];
 reg signed [24:0] pre2_1;
 (* use_dsp="yes" *) reg signed [47:0] prod2_1;
 always @(posedge clk) begin
   pre2_1 <= $signed({a2_1[23],a2_1}) + $signed({b2_1[23],b2_1});
   prod2_1 <= pre2_1 * -18'sd932;
 end
 wire signed [23:0] a2_2 = history[0];
 wire signed [23:0] b2_2 = history[5];
 reg signed [24:0] pre2_2;
 (* use_dsp="yes" *) reg signed [47:0] prod2_2;
 always @(posedge clk) begin
   pre2_2 <= $signed({a2_2[23],a2_2}) + $signed({b2_2[23],b2_2});
   prod2_2 <= pre2_2 * 18'sd3434;
 end
 wire signed [23:0] a2_3 = history[1];
 wire signed [23:0] b2_3 = history[4];
 reg signed [24:0] pre2_3;
 (* use_dsp="yes" *) reg signed [47:0] prod2_3;
 always @(posedge clk) begin
   pre2_3 <= $signed({a2_3[23],a2_3}) + $signed({b2_3[23],b2_3});
   prod2_3 <= pre2_3 * -18'sd10218;
 end
 wire signed [23:0] a2_4 = history[2];
 wire signed [23:0] b2_4 = history[3];
 reg signed [24:0] pre2_4;
 (* use_dsp="yes" *) reg signed [47:0] prod2_4;
 always @(posedge clk) begin
   pre2_4 <= $signed({a2_4[23],a2_4}) + $signed({b2_4[23],b2_4});
   prod2_4 <= pre2_4 * 18'sd40339;
 end
 reg signed [47:0] sum2_0_0;
 always @(posedge clk) sum2_0_0 <= prod2_0 + prod2_1;
 reg signed [47:0] sum2_0_1;
 always @(posedge clk) sum2_0_1 <= prod2_2 + prod2_3;
 reg signed [47:0] sum2_0_2;
 always @(posedge clk) sum2_0_2 <= prod2_4 + 48'sd0;
 reg signed [47:0] sum2_0_3;
 always @(posedge clk) sum2_0_3 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum2_1_0;
 always @(posedge clk) sum2_1_0 <= sum2_0_0 + sum2_0_1;
 reg signed [47:0] sum2_1_1;
 always @(posedge clk) sum2_1_1 <= sum2_0_2 + sum2_0_3;
 reg signed [47:0] sum2_2_0;
 always @(posedge clk) sum2_2_0 <= sum2_1_0 + sum2_1_1;
 wire signed [15:0] q2; wire sat2;
 fir_quantize #(.SHIFT(22),.BITS(16)) qnt2(.value(sum2_2_0),.result(q2),.sat(sat2));
 always @(posedge clk) begin
   if(rst) begin out_data[32 +: 16]<=0; out_sat[2]<=0; end
   else begin out_data[32 +: 16]<=q2; out_sat[2]<=sat2; end
 end
 wire signed [23:0] a3_0 = history[2];
 wire signed [23:0] b3_0 = 0;
 reg signed [24:0] pre3_0;
 (* use_dsp="yes" *) reg signed [47:0] prod3_0;
 always @(posedge clk) begin
   pre3_0 <= $signed({a3_0[23],a3_0}) + $signed({b3_0[23],b3_0});
   prod3_0 <= pre3_0 * 18'sd65536;
 end
 reg signed [47:0] sum3_0_0;
 always @(posedge clk) sum3_0_0 <= prod3_0 + 48'sd0;
 reg signed [47:0] sum3_0_1;
 always @(posedge clk) sum3_0_1 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum3_0_2;
 always @(posedge clk) sum3_0_2 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum3_0_3;
 always @(posedge clk) sum3_0_3 <= 48'sd0 + 48'sd0;
 reg signed [47:0] sum3_1_0;
 always @(posedge clk) sum3_1_0 <= sum3_0_0 + sum3_0_1;
 reg signed [47:0] sum3_1_1;
 always @(posedge clk) sum3_1_1 <= sum3_0_2 + sum3_0_3;
 reg signed [47:0] sum3_2_0;
 always @(posedge clk) sum3_2_0 <= sum3_1_0 + sum3_1_1;
 wire signed [15:0] q3; wire sat3;
 fir_quantize #(.SHIFT(22),.BITS(16)) qnt3(.value(sum3_2_0),.result(q3),.sat(sat3));
 always @(posedge clk) begin
   if(rst) begin out_data[48 +: 16]<=0; out_sat[3]<=0; end
   else begin out_data[48 +: 16]<=q3; out_sat[3]<=sat3; end
 end
endmodule
