set root [file normalize [file join [file dirname [info script]] ../..]]
if {[version -short] ne "2025.2"} {error "Requires Vivado 2025.2"}
set out [file join $root reports instrument_stage4]
file mkdir $out
create_project -in_memory -part xczu27dr-fsve1156-2-i
read_ip [file join $root build ip_probe_2025_2 calibrator_ip_probe.srcs sources_1 ip capture_ram_probe capture_ram_probe.xci]
read_verilog -sv [file join $root rtl/generated/calibrator_contract_pkg.sv]
read_verilog -sv [file join $root rtl/generated/capture_event_pkg.sv]
read_verilog -sv [file join $root rtl/replay/replay_control_layout_pkg.sv]
read_verilog -sv [file join $root rtl/calibrator_top.sv]
read_verilog -sv [file join $root rtl/arithmetic/complex_cal_core.sv]
read_verilog -sv [file join $root rtl/arithmetic/fixed_round_sat.sv]
read_verilog -sv [file join $root rtl/arithmetic/fractional_delay.sv]
read_verilog -sv [file join $root rtl/arithmetic/fractional_delay_pipelined.sv]
read_verilog -sv [file join $root rtl/arithmetic/fractional_delay_profile.sv]
read_verilog -sv [file join $root rtl/arithmetic/rx_cal_executor.sv]
read_verilog -sv [file join $root rtl/arithmetic/target_complex_operator.sv]
read_verilog -sv [file join $root rtl/arithmetic/tx_cal_executor.sv]
read_verilog -sv [file join $root rtl/backend/dac_stream_adapter.sv]
read_verilog -sv [file join $root rtl/backend/fir_tx_fir75.sv]
read_verilog -sv [file join $root rtl/backend/fir_tx_hb19.sv]
read_verilog -sv [file join $root rtl/backend/fir_tx_lane.sv]
read_verilog -sv [file join $root rtl/backend/tx_channel_router.sv]
read_verilog -sv [file join $root rtl/backend/tx_processing_chain.sv]
read_verilog -sv [file join $root rtl/capture/calibrator_capture_pipeline.sv]
read_verilog -sv [file join $root rtl/capture/calibrator_capture_system.sv]
read_verilog -sv [file join $root rtl/capture/capture_admission_bridge.sv]
read_verilog -sv [file join $root rtl/capture/capture_bank_array.sv]
read_verilog -sv [file join $root rtl/capture/capture_bank_manager.sv]
read_verilog -sv [file join $root rtl/capture/capture_pdw_writer.sv]
read_verilog -sv [file join $root rtl/capture/capture_producer_tracker.sv]
read_verilog -sv [file join $root rtl/capture/capture_ram.sv]
read_verilog -sv [file join $root rtl/capture/capture_range_select.sv]
read_verilog -sv [file join $root rtl/capture/capture_record_system.sv]
read_verilog -sv [file join $root rtl/capture/capture_reset_coordinator.sv]
read_verilog -sv [file join $root rtl/capture/capture_statistics_reader.sv]
read_verilog -sv [file join $root rtl/capture/frame_header_builder.sv]
read_verilog -sv [file join $root rtl/capture/frozen_record_reader.sv]
read_verilog -sv [file join $root rtl/capture/noise_snapshot.sv]
read_verilog -sv [file join $root rtl/capture/noise_window_energy.sv]
read_verilog -sv [file join $root rtl/capture/pulse_context_join.sv]
read_verilog -sv [file join $root rtl/capture/pulse_context_pool.sv]
read_verilog -sv [file join $root rtl/capture/pulse_detector.sv]
read_verilog -sv [file join $root rtl/capture/pulse_qualification_engine.sv]
read_verilog -sv [file join $root rtl/capture/pulse_range_statistics.sv]
read_verilog -sv [file join $root rtl/capture/qualification_bank_commit.sv]
read_verilog -sv [file join $root rtl/capture/qualification_publish_bridge.sv]
read_verilog -sv [file join $root rtl/capture/qualification_record_source.sv]
read_verilog -sv [file join $root rtl/capture/range_linearity.sv]
read_verilog -sv [file join $root rtl/capture/range_qualification.sv]
read_verilog -sv [file join $root rtl/capture/record_dma_bridge.sv]
read_verilog -sv [file join $root rtl/capture/record_formatter.sv]
read_verilog -sv [file join $root rtl/control/aux_source_controller.sv]
read_verilog -sv [file join $root rtl/control/cdc_mailbox.sv]
read_verilog -sv [file join $root rtl/control/coeff_reload_bridge.sv]
read_verilog -sv [file join $root rtl/control/csr_control_axi.sv]
read_verilog -sv [file join $root rtl/control/event_mailbox.sv]
read_verilog -sv [file join $root rtl/control/rf_safety_interlock.sv]
read_verilog -sv [file join $root rtl/data/axis_record_fifo.sv]
read_verilog -sv [file join $root rtl/data/record_descriptor_arbiter.sv]
read_verilog -sv [file join $root rtl/data/record_upload_groups.sv]
read_verilog -sv [file join $root rtl/data/record_upload_path.sv]
read_verilog -sv [file join $root rtl/frontend/channel_epoch_aligner.sv]
read_verilog -sv [file join $root rtl/frontend/fir_quantize.sv]
read_verilog -sv [file join $root rtl/frontend/fir_rx_fir75.sv]
read_verilog -sv [file join $root rtl/frontend/fir_rx_hb19.sv]
read_verilog -sv [file join $root rtl/frontend/fir_rx_lane.sv]
read_verilog -sv [file join $root rtl/frontend/native_overload_monitor.sv]
read_verilog -sv [file join $root rtl/frontend/rfdc_stream_adapter.sv]
read_verilog -sv [file join $root rtl/generated/fractional_delay_coeff_rom.sv]
read_verilog -sv [file join $root rtl/monitor/tx_reference_analyzer.sv]
read_verilog -sv [file join $root rtl/replay/calibrator_replay_system.sv]
read_verilog -sv [file join $root rtl/replay/frozen_replay_reader.sv]
read_verilog -sv [file join $root rtl/replay/replay_descriptor_queue.sv]
read_verilog -sv [file join $root rtl/replay/replay_legality_checker.sv]
read_verilog -sv [file join $root rtl/replay/replay_processing_chain.sv]
read_verilog -sv [file join $root rtl/replay/replay_task_dispatcher.sv]
read_verilog -sv [file join $root rtl/source/awg_load_cdc_wrapper.sv]
read_verilog -sv [file join $root rtl/source/awg_reader.sv]
read_verilog -sv [file join $root rtl/source/dds_burst_control.sv]
read_verilog -sv [file join $root rtl/source/dds_nco_wrapper.sv]
read_verilog -sv [file join $root rtl/source/generated_tx_sources.sv]
read_verilog -sv [file join $root rtl/source/tx_source_mux.sv]
read_verilog -sv [file join $root rtl/time/gsc_timebase.sv]
read_verilog -sv [file join $root rtl/top/calibrator_dataplane_system.sv]
read_verilog -sv [file join $root rtl/top/calibrator_transmit_system.sv]
read_verilog -sv [file join $root rtl/top/capture_replay_binding.sv]
read_verilog -sv [file join $root rtl/generated/command_gateway_pkg.sv]
read_verilog -sv [file join $root rtl/generated/instrument_control_pkg.sv]
read_verilog -sv [file join $root rtl/control/command_gateway_axi.sv]
read_verilog -sv [file join $root rtl/control/instrument_command_executor.sv]
read_verilog -sv [file join $root rtl/frontend/calibrator_receive_frontend.sv]
read_verilog -sv [file join $root rtl/capture/receive_event_producer.sv]
read_verilog -sv [file join $root rtl/top/calibrator_instrument_core.sv]
synth_design -top calibrator_instrument_core -mode out_of_context -part xczu27dr-fsve1156-2-i
create_clock -name clk_rf -period 8.000 [get_ports rf_clk]
create_clock -name clk_mem -period 5.000 [get_ports mem_clk]
create_clock -name clk_ctrl -period 10.000 [get_ports ctrl_clk]
set blackboxes [get_cells -quiet -hier -filter {IS_BLACKBOX == 1}]
if {[llength $blackboxes]} {error "Unresolved blackboxes: $blackboxes"}
report_utilization -file [file join $out utilization.rpt]
report_timing_summary -report_unconstrained -file [file join $out timing_synth.rpt]
check_timing -verbose -file [file join $out check_timing.rpt]
report_cdc -details -file [file join $out cdc.rpt]
set f [open [file join $out configuration.txt] w]
puts $f "VIVADO=[version -short] TOP=calibrator_instrument_core BLACKBOX_COUNT=[llength $blackboxes]"
close $f
write_checkpoint -force [file join $out synth.dcp]
puts INSTRUMENT_STAGE4_SYNTH_COMPLETE
close_project
exit
