% Generated from contracts/event_format.json
function c=capture_event_constants()
c.EVENT_BYTES=uint32(64);
c.EVENT_CAPTURE_TAG=uint32(65537);
c.EVENT_TAG_OFFSET=uint32(0);
c.EVENT_FLAGS_OFFSET=uint32(4);
c.EVENT_PULSE_ID_OFFSET=uint32(8);
c.EVENT_OWNER_EPOCH_OFFSET=uint32(16);
c.EVENT_CONFIG_ID_OFFSET=uint32(24);
c.EVENT_TOA_GSC_OFFSET=uint32(28);
c.EVENT_WIDTH_TICKS_OFFSET=uint32(36);
c.EVENT_PEAK_POWER_OFFSET=uint32(40);
c.EVENT_ENERGY_SUM_OFFSET=uint32(44);
c.EVENT_SELECTED_RANGE_OFFSET=uint32(52);
c.EVENT_RESERVED_OFFSET=uint32(56);
c.EVENT_TOA_VALID=uint32(1);
c.EVENT_WIDTH_VALID=uint32(2);
c.EVENT_PEAK_VALID=uint32(4);
c.EVENT_ENERGY_VALID=uint32(8);
c.EVENT_SELECTED_VALID=uint32(16);
end
