% Generated from contracts/fault_event_format.json
function c=fault_event_constants()
c.FAULT_EVENT_BYTES=uint32(64);
c.FAULT_EVENT_TAG=uint32(262145);
c.FAULT_EVENT_TAG_OFFSET=uint32(0);
c.FAULT_EVENT_FLAGS_OFFSET=uint32(4);
c.FAULT_EVENT_OCCURRENCES_OFFSET=uint32(8);
c.FAULT_EVENT_RESERVED_HEADER_OFFSET=uint32(12);
c.FAULT_EVENT_SNAPSHOT_TAG_OFFSET=uint32(16);
c.FAULT_EVENT_SNAPSHOT_FLAGS_OFFSET=uint32(20);
c.FAULT_EVENT_CONFIG_ID_OFFSET=uint32(24);
c.FAULT_EVENT_RF_STATE_OFFSET=uint32(28);
c.FAULT_EVENT_NORMALIZED_INPUTS_OFFSET=uint32(32);
c.FAULT_EVENT_LOGICAL_OUTPUTS_OFFSET=uint32(36);
c.FAULT_EVENT_OBSERVATION_GSC_OFFSET=uint32(40);
c.FAULT_EVENT_RESERVED_TAIL_OFFSET=uint32(48);
c.FAULT_EVENT_COUNT_SATURATED=uint32(1);
end
