% Generated from contracts/replay_identity_event.json
function c=replay_identity_event_constants()
c.REPLAY_IDENTITY_BYTES=uint32(64);
c.REPLAY_IDENTITY_TAG=uint32(393217);
c.REPLAY_IDENTITY_TAG_OFFSET=uint32(0);
c.REPLAY_IDENTITY_RESERVED_OFFSET=uint32(4);
c.REPLAY_IDENTITY_TOKEN_OFFSET=uint32(8);
c.REPLAY_IDENTITY_TASK_ID_OFFSET=uint32(16);
c.REPLAY_IDENTITY_PULSE_ID_OFFSET=uint32(24);
c.REPLAY_IDENTITY_OWNER_EPOCH_OFFSET=uint32(32);
c.REPLAY_IDENTITY_GENERATION_OFFSET=uint32(40);
c.REPLAY_IDENTITY_CONFIG_ID_OFFSET=uint32(48);
c.REPLAY_IDENTITY_FIR_ID_OFFSET=uint32(52);
c.REPLAY_IDENTITY_SOURCE_EPOCH_OFFSET=uint32(56);
c.REPLAY_IDENTITY_GROUP_OFFSET=uint32(60);
c.REPLAY_IDENTITY_BANK_OFFSET=uint32(62);
end
