% Generated from contracts/tx_lifecycle_event.json
function c=tx_lifecycle_event_constants()
c.TX_LIFECYCLE_BYTES=uint32(64);
c.TX_LIFECYCLE_TAG=uint32(327681);
c.TX_LIFECYCLE_TAG_OFFSET=uint32(0);
c.TX_LIFECYCLE_FLAGS_OFFSET=uint32(4);
c.TX_LIFECYCLE_SOURCE_OFFSET=uint32(8);
c.TX_LIFECYCLE_REASON_OFFSET=uint32(12);
c.TX_LIFECYCLE_COMMAND_SEQUENCE_OFFSET=uint32(16);
c.TX_LIFECYCLE_CONFIG_ID_OFFSET=uint32(20);
c.TX_LIFECYCLE_TOKEN_OFFSET=uint32(24);
c.TX_LIFECYCLE_ACCEPT_GSC_OFFSET=uint32(32);
c.TX_LIFECYCLE_DRAIN_GSC_OFFSET=uint32(40);
c.TX_LIFECYCLE_RETIRE_GSC_OFFSET=uint32(48);
c.TX_LIFECYCLE_RESERVED_OFFSET=uint32(56);
c.TX_LIFECYCLE_DIGITAL_DRAINED=uint32(1);
c.TX_LIFECYCLE_TIME_VALID=uint32(2);
c.TX_LIFECYCLE_SINK_CONFIRMED=uint32(4);
c.TX_LIFECYCLE_SOURCE_DDS=uint32(1);
c.TX_LIFECYCLE_SOURCE_AWG=uint32(2);
c.TX_LIFECYCLE_SOURCE_REPLAY=uint32(3);
c.TX_LIFECYCLE_REASON_NORMAL=uint32(0);
c.TX_LIFECYCLE_REASON_STOP=uint32(1);
c.TX_LIFECYCLE_REASON_SAFETY=uint32(2);
c.TX_LIFECYCLE_REASON_MUTE=uint32(3);
c.TX_LIFECYCLE_REASON_REPLAY_ABORT=uint32(4);
end
