# Generated by generate_fine_layout.py. Integer fields retain ABI units.
import struct
FIELDS = {'tag': (0, 'I'), 'flags': (4, 'I'), 'pulse_id': (8, 'Q'), 'owner_epoch': (16, 'Q'), 'generation': (24, 'Q'), 'config_id': (32, 'I'), 'range_id': (36, 'B'), 'bank_id': (37, 'B'), 'selected': (38, 'B'), 'channel_valid_mask': (39, 'B'), 'gsc_first': (40, 'Q'), 'h_rise_index_q16': (48, 'I'), 'h_fall_index_q16': (52, 'I'), 'v_rise_index_q16': (56, 'I'), 'v_fall_index_q16': (60, 'I'), 'h_peak_power': (64, 'I'), 'v_peak_power': (68, 'I'), 'h_mean_body_power': (72, 'I'), 'v_mean_body_power': (76, 'I'), 'h_residual_frequency_hz': (80, 'i'), 'v_residual_frequency_hz': (84, 'i'), 'h_chirp_rate_hz_per_s': (88, 'q'), 'v_chirp_rate_hz_per_s': (96, 'q'), 'hv_phase_q31_turn': (104, 'i'), 'h_snr_q16': (108, 'I'), 'v_snr_q16': (112, 'I'), 'edge_quality': (116, 'I'), 'spectral_quality': (120, 'I'), 'reserved': (124, 'I')}
def decode(data):
    if len(data)!=128:
        raise ValueError('Fine PDW must be exactly 128 bytes')
    result={name:struct.unpack_from('<'+fmt,data,offset)[0] for name,(offset,fmt) in FIELDS.items()}
    if result['tag']!=0x40001 or result['reserved']!=0:
        raise ValueError('Fine PDW tag/reserved mismatch')
    return result
