"""Exact unsigned256 edge-variance microprogram; coefficients are signed48 front-end terms."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OPS={'add':0,'sub':1,'mul':2,'div':3,'sh16':4,'sh32':5,'min1':6,'u64':7,'select':8,'halt':9}
PROGRAM=[]
def emit(op,d=0,a=0,b=0):PROGRAM.append((OPS[op],d,a,b))
# r0=1 r1=kQ16 r2=|delta| r3=|offset| r4=|slope| r5=|root numerator|
# r6=D r7=m r8=|m*num-slope*sx| r9=noise r10=max(threshold-noise,0)
# r11..18=absolute residuals, r19=2; r20..31=shared temporaries/results.
emit('mul',20,9,9);emit('mul',21,9,10);emit('add',21,21,21);emit('add',22,20,21);emit('min1',22,22)
emit('sub',23,0,0)
for r in range(11,19):emit('mul',20,r,r);emit('add',23,23,20)
emit('mul',24,6,6);emit('sub',20,7,19);emit('mul',24,24,20)
emit('mul',20,22,24);emit('sub',21,23,20);emit('select')
emit('sh16',20,3);emit('div',29,20,2);emit('add',29,29,1)
emit('sh16',20,5);emit('div',30,20,4);emit('add',30,30,1)
emit('sub',20,2,3);emit('mul',20,20,20);emit('mul',21,3,3);emit('add',20,20,21)
emit('mul',20,20,22);emit('sh32',20,20);emit('mul',21,2,2);emit('mul',21,21,21)
emit('div',27,20,21);emit('u64',27,27)
emit('mul',20,4,4);emit('mul',21,6,20);emit('mul',23,8,8);emit('add',21,21,23)
emit('mul',21,21,6);emit('mul',21,21,25);emit('sh32',21,21)
emit('mul',20,20,20);emit('mul',20,20,7);emit('mul',20,20,26);emit('div',28,21,20);emit('u64',28,28)
emit('mul',20,29,28);emit('mul',21,30,27);emit('add',20,20,21);emit('add',21,27,28)
emit('div',31,20,21);emit('halt')

def wide_reference(op,a,b,rounding=True):
 """Independent integer operation plus exact request-to-valid cycle contract."""
 limit=(1<<256)-1
 if not 0<=a<=limit or not 0<=b<=limit:raise ValueError('unsigned256')
 if op==0:value=a+b;fault=value>limit;cycles=8
 elif op==1:value=a-b;fault=value<0;cycles=8
 elif op==2:value=a*b;fault=value>limit;cycles=258+16*b.bit_count()
 elif b==0:return 0,True,0
 else:
  value,rem=divmod(a,b);up=rounding and 2*rem>=b
  value+=up;fault=value>limit;cycles=2561 if not rounding else (2578 if up else 2570)
 return value&limit,bool(fault),cycles

def candidate_reference(power,offset,index,threshold,noise,rising):
 """Finite integer microprogram model with explicit latency, no Fraction/float.

 It intentionally does not search crossings or determine window availability.
 fine_fixed.edge_pair_q16 remains the independent rational numerical oracle.
 """
 from fine_fixed import FixedEdge
 m=len(power);cycles=1
 if not 2<=m<=8 or not 0<=offset<=3 or offset+1>=m or m>offset+5 or index<offset or index>=16383:
  return FixedEdge(quality=64),cycles
 if noise>1<<31:return FixedEdge(quality=128),cycles
 p0,p1=power[offset:offset+2]
 if not (p0<threshold<=p1 if rising else p0>=threshold>p1):return FixedEdge(quality=2 if rising else 4),cycles
 if m<4:return FixedEdge(quality=64),cycles
 if any(not 0<=p<=1<<31 for p in power):raise ValueError('power')
 xs=[j-offset for j in range(m)];sy=sum(power);sx=sum(xs);sxx=sum(x*x for x in xs);sxy=sum(x*p for x,p in zip(xs,power))
 d=m*sxx-sx*sx;slope=m*sxy-sx*sy;intercept=sy*sxx-sx*sxy;num=threshold*d-intercept
 cycles=m+6
 if not slope or (slope>0)!=rising:return FixedEdge(quality=8),cycles
 if num and (num<0)!=(slope<0) or abs(num)>abs(slope):return FixedEdge(quality=96),cycles
 r=[0]*32;r[:11]=[1,index<<16,abs(p1-p0),abs(threshold-p0),abs(slope),abs(num),d,m,abs(m*num-slope*sx),noise,max(threshold-noise,0)]
 for j,(x,p) in enumerate(zip(xs,power)):r[11+j]=abs(d*p-intercept-slope*x)
 r[19]=2;cycles=5*m+9;borrow=False
 for pc,(op,dst,a,b) in enumerate(PROGRAM):
  cycles+=3
  if op<=3:
   value,fault,latency=wide_reference(op,r[a],r[b]);cycles+=latency+2
   if fault and not(op==1 and PROGRAM[pc+1][0]==8):return FixedEdge(quality=256),cycles
   r[dst]=value;borrow=fault
  elif op in (4,5):
   value=r[a]<<(16 if op==4 else 32)
   if value.bit_length()>256:return FixedEdge(quality=256),cycles
   r[dst]=value
  elif op in (6,7):
   if op==7 and r[a].bit_length()>64:return FixedEdge(quality=256),cycles
   r[dst]=max(1,r[a])
  elif op==8:r[25],r[26]=(r[22],1) if borrow else (r[23],r[24])
  elif op==9:
   if any(r[j].bit_length()>32 for j in [29,30,31]):return FixedEdge(quality=256),cycles
   return FixedEdge(r[31],r[29],r[30],r[27],r[28],True,0),cycles
 raise AssertionError('missing halt')

def source():
 lines=['// Generated by tools/fine_edge_program.py; do not edit.',
  'package fine_edge_program_pkg;',f' localparam integer EDGE_PROGRAM_LENGTH={len(PROGRAM)};',
  f' localparam integer EDGE_COMPARE_PC={next(i for i,x in enumerate(PROGRAM) if x[0]==8)-1};',
  ' function automatic [18:0] edge_instruction(input [6:0] pc);','  case(pc)']
 for pc,(op,d,a,b) in enumerate(PROGRAM):
  lines.append(f"   7'd{pc}:edge_instruction=19'h{(op<<15)|(d<<10)|(a<<5)|b:05x};")
 lines+=['   default:edge_instruction=19\'h48000;','  endcase',' endfunction','endpackage','']
 return '\n'.join(lines)

if __name__=='__main__':
 path=ROOT/'rtl/generated/fine_edge_program_pkg.sv';path.write_text(source())
 print(f'Generated {len(PROGRAM)} edge instructions')
