"""Reproduce the 63-tap,256-phase Q16 Kaiser fractional-delay candidate.
The sweep target is internal numerical validation, not physical board acceptance.
"""
from pathlib import Path
import hashlib,json,math
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
TAPS=63;PHASES=256;FRAC=16;BETA=8.0;FS=125000000;FFT_N=65536
n=np.arange(TAPS,dtype=float)
rows=[];max_amp=(-1,None,None);max_phase=(-1,None,None)
frequencies=np.arange(math.floor(.4*FFT_N)+1)*FS/FFT_N
# Evaluate the exact50MHz endpoint in addition to all FFT grid points.
endpoint=np.exp(-2j*np.pi*.4*n)
for phase in range(PHASES):
    mu=phase/PHASES
    h=np.sinc(n-31-mu)*np.kaiser(TAPS,BETA)
    h/=h.sum()
    q=np.rint(h*(1<<FRAC)).astype(np.int64)
    q[31]+=(1<<FRAC)-int(q.sum())
    assert np.all(q>=-131072) and np.all(q<=131071)
    rows.append(q)
    z=np.fft.rfft(q/(1<<FRAC),FFT_N)[:len(frequencies)]
    z*=np.exp(2j*np.pi*frequencies/FS*(31+mu))
    z=np.append(z,np.dot(q/(1<<FRAC),endpoint)*np.exp(2j*np.pi*.4*(31+mu)))
    f=np.append(frequencies,50000000)
    ae=np.abs(20*np.log10(np.abs(z)));pe=np.abs(np.angle(z,deg=True))
    ai=int(np.argmax(ae));pi=int(np.argmax(pe))
    if ae[ai]>max_amp[0]:max_amp=(float(ae[ai]),phase,float(f[ai]))
    if pe[pi]>max_phase[0]:max_phase=(float(pe[pi]),phase,float(f[pi]))
text=''.join(f'{sum((int(v)&262143)<<(18*k) for k,v in enumerate(row)):0284x}\n' for row in rows)
sha=hashlib.sha256(text.encode('ascii')).hexdigest();version=int(sha[:8],16)
(ROOT/'rtl/coefficients').mkdir(exist_ok=True)
(ROOT/'rtl/coefficients/fractional_delay_63x256_q16.mem').write_text(text,encoding='ascii',newline='\n')
case_rows='\n'.join(f"    8'd{phase}: coefficients=1134'h{row};" for phase,row in enumerate(text.splitlines()))
rom=f'''// Generated by tools/generate_fractional_delay.py; coefficientSHA256 {sha}
// Portable immutable coefficients: no runtime file access or current-directory dependency.
module fractional_delay_coeff_rom(
 input wire [7:0] phase,output reg [1133:0] coefficients,output wire [31:0] table_version);
 always_comb begin
   case(phase)
{case_rows}
     default:coefficients=1134'd0;
   endcase
 end
 assign table_version=32'h{version:08x};
endmodule
'''
(ROOT/'rtl/generated/fractional_delay_coeff_rom.sv').write_text(rom)
report={'schema_version':'1.0','profile':'FD63_KAISER8_PHASE256_Q16','status':'INTERNAL_DIGITAL_TARGET_PASSED_NOT_BOARD_ACCEPTED','generator':'tools/generate_fractional_delay.py','sample_rate_hz':FS,'taps':TAPS,'phases':PHASES,'kaiser_beta':BETA,'coefficient_bits':18,'fractional_bits':FRAC,'rounding':'nearest ties to even; central tap adjusted so integer sum=65536','coefficient_sha256':sha,'table_version_u32':version,'table_version_hex':f'{version:08x}','deployment':'generated embeddedROM constants; .mem is golden/review data only; no runtime file path','packing':'256 lines indexed phase; tap0 in least-significant18bits, each row1134 meaningful bits; two padding zero bits in284hex digits','delay_samples':'31+phase/256; eight pipeline register stages additional and distinct','pipeline_stages':8,'input_sample_to_corresponding_output_edge_offset':7,'phase_policy':'causal delay; do not compensate existing FIR group delay twice','scan':{'frequency_grid_points_per_phase':len(frequencies)+1,'grid_step_hz':FS/FFT_N,'band_hz':[-50000000,50000000],'method':'FFT grid plus exact50MHz endpoint; negative-frequency errors equal by real coefficient conjugacy; remove ideal31+mu phase','not_continuous_frequency_proof':True},'internal_targets':{'amplitude_error_db':0.01,'phase_error_deg':0.1,'authority':'engineering numerical target for this candidate; not an existing approved system/board allocation'},'metrics':{'max_amplitude_error_db':max_amp[0],'amplitude_worst_phase':max_amp[1],'amplitude_worst_frequency_hz':max_amp[2],'max_phase_error_deg':max_phase[0],'phase_worst_phase':max_phase[1],'phase_worst_frequency_hz':max_phase[2]},'limitations':['Physical timing evidence is separate in reports/calibration_timing_summary.json; coefficient generation alone is not hardware timing proof','No board/radio precision validation','No approved system error-budget allocation','Frequency sweep is finite-grid, not an analytic supremum bound','Finite burst requires31+mu group delay scheduling,62zero tail samples and eight-stage pipeline drain before safe boundary']}
assert max_amp[0]<=.01 and max_phase[0]<=.1
(ROOT/'contracts/fractional_delay_profile.json').write_text(json.dumps(report,indent=2)+'\n')
print(f'PASS FD63 numerical candidate: amplitude {max_amp[0]:.9f}dB, phase {max_phase[0]:.9f}deg; all256 phases; version{version:08x}')

