"""Validate the frozen numeric/layout subset and deterministically export it."""
import argparse, hashlib, json, pathlib, re
ROOT = pathlib.Path(__file__).resolve().parents[1]
TYPES = {'u8':1,'u16':2,'u32':4,'u64':8,'i32':4,'i64':8}
def load_contracts(directory):
 return {p.stem:json.loads(p.read_text(encoding='utf-8-sig')) for p in sorted(pathlib.Path(directory).glob('*.json'))}
def require(ok,message):
 if not ok: raise ValueError(message)
def disjoint(spans):
 ordered=sorted(spans)
 for (a,b,n),(c,d,m) in zip(ordered,ordered[1:]):require(b<=c,f'overlap: {n} / {m}')
def validate(c):
 address_spans=[]
 for segment in c['address_map']['segments']:
  base=int(segment['base_hex'],16);size=segment['size_bytes']
  require(base>=0 and size>0 and base+size<=2**64,'address bounds')
  address_spans.append((base,base+size,segment['name']))
 disjoint(address_spans)
 f,r,s=c['frame_format'],c['register_map'],c['system_contract']
 require(f['abi_version']==r['abi_version']==s['frame_abi_version']==5,'ABI mismatch')
 require(f['byte_order']=='little' and f['header_bytes']==128,'unsupported header encoding')
 spans=[]; names=set()
 for x in f['header']:
  n,o,z=x['name'],x['offset_bytes'],x['size_bytes'];require(n not in names,'duplicate header name');names.add(n)
  require(o>=0 and z>0 and o+z<=128,'header bounds');require(x['type']=='bytes' or TYPES.get(x['type'])==z,'header type width')
  spans.append((o,o+z,n))
 disjoint(spans);require(sum(b-a for a,b,_ in spans)==128,'header gap')
 spans=[];names=set()
 for x in r['registers']:
  n,o,w=x['name'],int(x['offset_hex'],16),x['width_bits'];require(n not in names,'duplicate register name');names.add(n)
  require(w==32 and o>=0 and o%4==0 and o+4<=65536,'register bounds/alignment');require(x['access'] in ('RO','RW','WO','W1C'),'register access')
  require(type(x['reset']) is int and 0<=x['reset']<2**w,'reset width');spans.append((o,o+4,n))
 for region,name in r['reserved_groups'].items():
  a,b=region.split('-');a,b=int(a,16),int(b,16)+1
  require(0<=a<b<=65536 and a%4==0 and b%4==0,'reserved region bounds/alignment')
  spans.append((a,b,name))
 table=r['bank_snapshot_table'];base=int(table['base_hex'],16);stride=table['stride_bytes']
 require(type(stride) is int and stride>0 and stride%4==0,'snapshot stride')
 require(type(table['rows']) is int and table['rows']>0,'snapshot row count')
 require(base>=0 and base%4==0 and base+stride*table['rows']<=65536,'snapshot region bounds/alignment')
 spans.append((base,base+stride*table['rows'],'bank snapshot'));disjoint(spans)
 fields=[(x['offset'],x['offset']+4,x['name']) for x in table['fields']];disjoint(fields)
 require(all(a>=0 and a%4==0 and b<=stride for a,b,_ in fields),'snapshot bounds')
 require(f['payload']['bytes_per_sample']==8 and f['payload']['max_samples']==s['capture']['samples_per_bank'],'payload contract')
 for suffix,extra in [('without_trailer',0),('with_trailer',f['trailer']['bytes'])]:
  require(f['max_record_bytes_'+suffix]==128+8*f['payload']['max_samples']+extra,'record maximum')
 for name,stage in c['fir_coefficients']['stages'].items():
  v=stage['integers']; bits=stage['coefficient_bits'];require(len(v)==stage['taps'],'tap count')
  require(all(type(x)is int and -2**(bits-1)<=x<2**(bits-1) for x in v),'coefficient width')
  require(stage['effective_divisor']==2**stage['coefficient_fraction_bits'],'coefficient scale')
 require(s['rates']['rfdc_complex_hz']==s['rates']['core_complex_hz']*s['rates']['pl_decimation'],'RX rate relation')
 require(s['capture']['raw_bytes_initial']==s['capture']['samples_per_bank']*8*s['capture']['initial_bank_count']*s['capture']['stream_group_count'],'bank bytes')
def constants(c):
 out={}
 for r in c['register_map']['registers']:
  out['REG_'+r['name']]=int(r['offset_hex'],16);out['REG_'+r['name']+'_RESET']=r['reset']
 for section in ('rates','clock_targets','capture','rx_channels'):
  for k,v in c['system_contract'][section].items():
   if type(v) is int:out['SYS_'+section.upper()+'_'+k.upper()]=v
 f=c['frame_format'];out.update(FRAME_ABI_VERSION=f['abi_version'],FRAME_HEADER_BYTES=f['header_bytes'],FRAME_PAYLOAD_SAMPLE_BYTES=f['payload']['bytes_per_sample'],FRAME_MAX_SAMPLES=f['payload']['max_samples'],FRAME_TRAILER_BYTES=f['trailer']['bytes'],FRAME_MAGIC=int(f['header'][0]['meaning'],16),FRAME_TRAILER_MAGIC=int(f['trailer']['magic_hex'],16))
 for x in f['header']:
  out['FRAME_'+x['name'].upper()+'_OFFSET']=x['offset_bytes'];out['FRAME_'+x['name'].upper()+'_BYTES']=x['size_bytes']
 for b,n in f['quality_flag_bits'].items():out['QUALITY_'+n]=1<<int(b)
 return out
def generate(c,destination):
 validate(c);destination=pathlib.Path(destination);out=constants(c)
 sv=['// Generated by tools/generate_contracts.py; do not edit.','package calibrator_contract_pkg;']
 ch=['/* Generated from contracts; do not edit. */','#ifndef CALIBRATOR_CONTRACT_H','#define CALIBRATOR_CONTRACT_H','#include <stdint.h>']
 for k,v in sorted(out.items()):
  width=32 if v<2**32 else 64;sv.append(f'  localparam logic [{width-1}:0] {k} = {width}\'d{v};');ch.append(f'#define {k} UINT{width}_C({v})')
 sv.append('endpackage');ch.append('#endif')
 outputs={'rtl/generated/calibrator_contract_pkg.sv':'\n'.join(sv)+'\n','sw/common/generated/calibrator_contract.h':'\n'.join(ch)+'\n'}
 for name,stage in c['fir_coefficients']['stages'].items():outputs[f'hw/coefficients/{name}.coe']='radix=10;\ncoefdata='+','.join(map(str,stage['integers']))+';\n'
 manifest={'scope':'validated layout and numeric exports only; hardware not validated','contracts_canonical_sha256':{k:hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest() for k,v in sorted(c.items())},'outputs_sha256':{k:hashlib.sha256(v.encode()).hexdigest() for k,v in sorted(outputs.items())},'residuals':['format_id numeric enum is unspecified; caller must supply it','DSP parameter arrays and task descriptors are outside this bounded generator']}
 outputs['reports/contract_abi_manifest.json']=json.dumps(manifest,indent=2,sort_keys=True)+'\n'
 for p,data in outputs.items():
  target=destination/p;target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(data.encode())
 return manifest
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--contracts',type=pathlib.Path,default=ROOT/'contracts');parser.add_argument('--output',type=pathlib.Path,default=ROOT);args=parser.parse_args();m=generate(load_contracts(args.contracts),args.output);print('Validated frozen contract subset; generated',len(m['outputs_sha256']),'artifacts')
