"""Linear CRC32C transform; balanced XOR network instead of serial byte logic."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def generate():
    lines=['// Generated by tools/generate_crc32c_parallel.py','package crc32c_parallel_pkg;']
    for width in (64,128):
        # Each integer tracks which input bits contribute over GF(2).
        state=[1<<i for i in range(32)]
        for k in range(width):
            feedback=state[0]^(1<<(32+k))
            state=state[1:]+[0]
            state=[v^feedback if (0x82f63b78>>i)&1 else v for i,v in enumerate(state)]
        lines.append(f' function automatic [31:0] crc{width}(input [31:0] c,input [{width-1}:0] d);')
        for i,mask in enumerate(state):
            terms=[f'c[{j}]' if j<32 else f'd[{j-32}]' for j in range(32+width) if (mask>>j)&1]
            lines.append(f'  crc{width}[{i}]='+ '^'.join(terms)+';')
        lines.append(' endfunction')
    lines.append('endpackage')
    return '\n'.join(lines)+'\n'
if __name__=='__main__':(ROOT/'rtl/generated/crc32c_parallel_pkg.sv').write_text(generate())
