"""Generate constant-folded symmetric SSR/polyphase FIR datapaths from frozen integers."""
import hashlib,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
raw=(ROOT/'contracts/fir_coefficients.json').read_bytes()
data=json.loads(raw)['stages']
HEADER='// Generated by tools/generate_fir_rtl.py; do not hand edit.\n// Coefficient JSON SHA256 '+hashlib.sha256(raw).hexdigest()+'\n'
def emit(path,text):
    p=ROOT/path;p.parent.mkdir(exist_ok=True,parents=True);p.write_text(HEADER+text)
emit('rtl/frontend/fir_quantize.sv', '''// Arithmetic floor plus unsigned residue implements convergent rounding for both signs.
module fir_quantize #(parameter integer SHIFT=17, BITS=16)(
 input wire signed [47:0] value, output wire signed [BITS-1:0] result, output wire sat);
 wire signed [48:0] base = $signed(value) >>> SHIFT;
 wire up = (value[SHIFT-1:0] > (48'd1 << (SHIFT-1))) ||
           ((value[SHIFT-1:0] == (48'd1 << (SHIFT-1))) && base[0]);
 wire signed [48:0] rounded = base + $signed({48'd0,up});
 localparam signed [48:0] HI = (49'sd1 << (BITS-1))-1;
 localparam signed [48:0] LO = -(49'sd1 << (BITS-1));
 assign sat = rounded > HI || rounded < LO;
 assign result = rounded > HI ? HI[BITS-1:0] : rounded < LO ? LO[BITS-1:0] : rounded[BITS-1:0];
endmodule
''')
spec=[('rx_hb19','RX_HB19_D2',4,2,16,24,11,False),('rx_fir75','RX_FIR75_D2',2,1,24,16,23,False),('tx_fir75','TX_FIR75_L2',1,2,16,24,10,True),('tx_hb19','TX_HB19_L2',2,4,24,16,22,True)]
latencies={};resources={}
for name,key,ins,outs,wi,wo,shift,interp in spec:
    coeff=data[key]['integers'];nt=len(coeff); branches=[]
    def sample(idx):
        if interp:
            if idx%2:return None
            idx//=2
        return f'$signed(in_data[{idx*wi} +: {wi}])' if idx>=0 else f'history[{-idx-1}]'
    for lane in range(outs):
        n=lane if interp else lane*2;terms=[]
        for k in range((nt+1)//2):
            c=coeff[k]
            assert c==coeff[nt-1-k]
            if not c:continue
            a=sample(n-k);b=sample(n-(nt-1-k)) if k!=nt-1-k else None
            if a is None and b is None:continue
            terms.append((c,a,b))
        branches.append(terms)
    levels=math.ceil(math.log2(max(map(len,branches))));lat=levels+3;latencies[name]=lat
    depth=nt if not interp else (nt+1)//2
    s=[f'''// Lane 0 is earliest. Valid gaps preserve sample history; reset clears history/valid.
// {key}: source COE SHA256 {data[key]['source_coe_sha256']}
// Pipeline: registered preadd, multiply, {levels} balanced sum levels, round/saturate.
// {lat} registers; accepted edge n -> output edge n+{lat-1}; II=1.
module fir_{name}(input wire clk,rst,in_valid,
 input wire [{ins*wi-1}:0] in_data, output wire out_valid,
 output reg [{outs*wo-1}:0] out_data, output reg [{outs-1}:0] out_sat);
 reg signed [{wi-1}:0] history[0:{depth-1}];
 reg [{lat-1}:0] valid_pipe;
 integer h;
 always @(posedge clk) begin
   if(rst) begin
     valid_pipe <= 0;
     for(h=0;h<{depth};h=h+1) history[h]<=0;
   end else begin
     valid_pipe <= {{valid_pipe[{lat-2}:0],in_valid}};
     if(in_valid) begin''']
    for j in range(depth): s.append(f'       history[{j}] <= '+(f'in_data[{(ins-1-j)*wi} +: {wi}]' if j<ins else f'history[{j-ins}]')+';')
    s+=['     end','   end',' end',f' assign out_valid=valid_pipe[{lat-1}];']
    for lane,terms in enumerate(branches):
        for t,(c,a,b) in enumerate(terms):
            s+=[f' wire signed [{wi-1}:0] a{lane}_{t} = {a or "0"};',f' wire signed [{wi-1}:0] b{lane}_{t} = {b or "0"};',f' reg signed [{wi}:0] pre{lane}_{t};',f' (* use_dsp="yes" *) reg signed [47:0] prod{lane}_{t};',f' always @(posedge clk) begin',f'   pre{lane}_{t} <= $signed({{a{lane}_{t}[{wi-1}],a{lane}_{t}}}) + $signed({{b{lane}_{t}[{wi-1}],b{lane}_{t}}});',f'   prod{lane}_{t} <= pre{lane}_{t} * '+('-' if c<0 else '')+f"18'sd{abs(c)};",' end']
        nodes=[f'prod{lane}_{t}' for t in range(len(terms))]+["48'sd0"]*((1<<levels)-len(terms))
        for level in range(levels):
            nxt=[]
            for t in range(len(nodes)//2):
                node=f'sum{lane}_{level}_{t}';s += [f' reg signed [47:0] {node};',f' always @(posedge clk) {node} <= {nodes[2*t]} + {nodes[2*t+1]};'];nxt.append(node)
            nodes=nxt
        s += [f' wire signed [{wo-1}:0] q{lane}; wire sat{lane};',f' fir_quantize #(.SHIFT({shift}),.BITS({wo})) qnt{lane}(.value({nodes[0]}),.result(q{lane}),.sat(sat{lane}));',f' always @(posedge clk) begin',f'   if(rst) begin out_data[{lane*wo} +: {wo}]<=0; out_sat[{lane}]<=0; end',f'   else begin out_data[{lane*wo} +: {wo}]<=q{lane}; out_sat[{lane}]<=sat{lane}; end',' end']
    s+=['endmodule\n'];emit(f'rtl/{"frontend" if not interp else "backend"}/fir_{name}.sv','\n'.join(s))
    resources[name]={'products_per_real_path':sum(map(len,branches)),'pipeline_registers':lat}
for direction,first,second,ins,outs in [('rx','rx_hb19','rx_fir75',4,1),('tx','tx_fir75','tx_hb19',1,4)]:
    delay=latencies[second]
    s=f'''// Two independent real histories implement one complex physical path.
// out_sat[0]=first stage, out_sat[1]=second stage, OR across lanes and I/Q.
module fir_{direction}_lane(input wire clk,rst,in_valid,
 input wire [{ins*16-1}:0] in_i,in_q, output wire out_valid,
 output wire [{outs*16-1}:0] out_i,out_q, output wire [1:0] out_sat);
 wire [47:0] mid_i,mid_q; wire mid_valid,unused_mid_valid,unused_out_valid;
 wire [1:0] sat1i,sat1q; wire [{outs-1}:0] sat2i,sat2q;
 fir_{first} fi(.clk(clk),.rst(rst),.in_valid(in_valid),.in_data(in_i),.out_valid(mid_valid),.out_data(mid_i),.out_sat(sat1i));
 fir_{first} fq(.clk(clk),.rst(rst),.in_valid(in_valid),.in_data(in_q),.out_valid(unused_mid_valid),.out_data(mid_q),.out_sat(sat1q));
 fir_{second} si(.clk(clk),.rst(rst),.in_valid(mid_valid),.in_data(mid_i),.out_valid(out_valid),.out_data(out_i),.out_sat(sat2i));
 fir_{second} sq(.clk(clk),.rst(rst),.in_valid(mid_valid),.in_data(mid_q),.out_valid(unused_out_valid),.out_data(out_q),.out_sat(sat2q));
 reg [{delay-1}:0] sat1_delay;
 always @(posedge clk) if(rst) sat1_delay<=0;
 else sat1_delay <= {{sat1_delay[{delay-2}:0],(|sat1i)|(|sat1q)}};
 assign out_sat={{(|sat2i)|(|sat2q),sat1_delay[{delay-1}]}};
endmodule
'''
    emit(f'rtl/{"frontend" if direction=="rx" else "backend"}/fir_{direction}_lane.sv',s)
(ROOT/'reports').mkdir(exist_ok=True)
(ROOT/'reports/fir_generated_structure.json').write_text(json.dumps(resources,indent=2)+'\n')
