"""Generate the dedicated replay-control ABI constants from the v0.5 contract."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
def render():
    task=json.loads((ROOT/'contracts/replay_contract.json').read_text())['replay_task']
    lines=['// Generated by tools/generate_replay_control_layout.py; do not edit.', 'package replay_control_layout_pkg;',f" localparam integer TASK_BITS={task['size_bytes']*8};"]
    for f in task['fields']:
        lines.append(f" localparam integer {f['name'].upper()}_BIT={f['offset_bytes']*8};")
    return '\n'.join(lines+['endpackage',''])
if __name__=='__main__':
    (ROOT/'rtl/replay/replay_control_layout_pkg.sv').write_text(render())
