"""Generate a 12-bit phase, Q16 phasor ROM and pipelined GSC evaluator."""
from pathlib import Path
import math
ROOT=Path(__file__).resolve().parents[1]
def render():
    rows='\n'.join(f"   12'd{k}:sine=18'sh{round(65536*math.sin(2*math.pi*k/4096)) & 0x3ffff:05x};" for k in range(4096))
    return '''// Generated by tools/generate_task_doppler.py. Phase arithmetic is modulo 2^48.
// Output belongs to phase_gsc at the NEXT consumer edge. Three pipeline stages
// predict three 4-tick RF cycles; timestamp mismatch invalidates clock jumps.
module task_doppler_phase(
 input wire clk,rst,load,cancel,input wire [63:0] gsc,reference_gsc,offset_ticks,
 input wire [47:0] step,initial_phase,
 output wire valid,output reg signed [17:0] phase_i,phase_q,
 output reg [63:0] phase_gsc
);
 reg active;reg [47:0] step_hold,phase_hold,reference_hold;
 reg [63:0] offset_hold;reg [47:0] delta,angle;
 reg [63:0] stamp0,stamp1;reg [2:0] v;
 wire [64:0] predicted={1'b0,gsc}+65'd12+{1'b0,offset_hold};
 wire [64:0] current_stamp={1'b0,gsc}+{1'b0,offset_hold};
 assign valid=active&&v[2]&&!rst&&!cancel&&!load&&!current_stamp[64]&&phase_gsc==current_stamp[63:0];
 function automatic signed [17:0] sine(input [11:0] a);
 begin case(a)
'''+rows+'''
   default:sine=0;
 endcase end endfunction
 always @(posedge clk)begin
  if(rst)begin
   active<=0;step_hold<=0;phase_hold<=0;reference_hold<=0;offset_hold<=0;
   delta<=0;angle<=0;stamp0<=0;stamp1<=0;v<=0;phase_i<=0;phase_q<=0;phase_gsc<=0;
  end else begin
   v<={v[1:0],active&&!predicted[64]};
   delta<=predicted[47:0]-reference_hold;stamp0<=predicted[63:0];
   angle<=delta*step_hold+phase_hold;stamp1<=stamp0;
   phase_i<=sine(angle[47:36]+12'd1024);phase_q<=sine(angle[47:36]);phase_gsc<=stamp1;
   if(load)begin
    active<=1;step_hold<=step;phase_hold<=initial_phase;reference_hold<=reference_gsc[47:0];offset_hold<=offset_ticks;v<=0;
   end
   if(cancel)begin active<=0;v<=0;end
  end
 end
endmodule
'''
if __name__=='__main__':
    (ROOT/'rtl/replay/task_doppler_phase.sv').write_text(render())
