"""Single-source Fine sidecar ABI constants and raw integer decoder."""
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1]
def outputs():
 d=json.loads((ROOT/'contracts/fine_pdw_format.json').read_text())
 t=json.loads((ROOT/'contracts/fine_result_transport.json').read_text())
 occupied=set();formats={};sv=['// Generated by generate_fine_layout.py','package fine_pdw_pkg;']
 h=['/* Generated by generate_fine_layout.py; explicit byte decoding, no packed C ABI. */','#ifndef CAL_FINE_PDW_LAYOUT_H','#define CAL_FINE_PDW_LAYOUT_H']
 m=['function layout = fine_pdw_layout()', '% Generated; offsets are zero-based bytes.']
 constants={'FINE_PDW_BYTES':d['bytes'],'FINE_PDW_TAG':int(d['tag_hex'],16),
  'FINE_TRANSPORT_REVISION':t['schema_version'],'FINE_QUEUE_DEPTH':t['queue_depth'],
  'FINE_IRQ_MASK':int(t['irq']['mask_hex'],16)}
 constants.update({'FINE_FLAG_'+name:value for name,value in d.get('flags',{}).items()})
 constants.update({name:value['opcode'] for name,value in t['commands'].items()})
 fmt={'u8':'B','u16':'H','u32':'I','u64':'Q','i32':'i','i64':'q'}
 for f in d['fields']:
  pos,size=f['offset_bytes'],f['size_bytes'];span=set(range(pos,pos+size))
  assert not occupied&span and max(span)<d['bytes'],f
  occupied|=span;formats[f['name']]=(pos,fmt[f['type']])
  constants['FINE_'+f['name'].upper()+'_OFFSET']=pos
  constants['FINE_'+f['name'].upper()+'_BIT']=pos*8
  constants['FINE_'+f['name'].upper()+'_WIDTH']=size*8
 assert len(occupied)==128
 for name,v in constants.items():
  sv.append(f' localparam integer {name}={v};');h.append(f'#define CAL_{name} {v}u');m.append(f'layout.{name} = {v};')
 sv.append('endpackage');h.append('#endif');m.append('end')
 py='''# Generated by generate_fine_layout.py. Integer fields retain ABI units.
import struct
'''+f'FIELDS = {formats!r}\n'+'''def decode(data):
    if len(data)!=128:
        raise ValueError('Fine PDW must be exactly 128 bytes')
    result={name:struct.unpack_from('<'+fmt,data,offset)[0] for name,(offset,fmt) in FIELDS.items()}
    if result['tag']!=0x40001 or result['reserved']!=0:
        raise ValueError('Fine PDW tag/reserved mismatch')
    return result
'''
 return {'rtl/generated/fine_pdw_pkg.sv':'\n'.join(sv)+'\n',
  'sw/common/include/fine_pdw_layout.h':'\n'.join(h)+'\n',
  'sw/matlab/fine_pdw_layout.m':'\n'.join(m)+'\n','tools/fine_pdw_codec.py':py}
if __name__=='__main__':
 for name,content in outputs().items():
  p=ROOT/name
  if '--check' in sys.argv:assert p.read_text()==content,name
  else:p.write_text(content)
 print('PASS Fine ABI generation consistency')
