// Integrated RF-domain data plane. Capture owns the sole bank array; replay
// consumes actual frozen leases and feeds the common DRFM/TXCAL/FIR/DAC path.
// Configuration transactions and normalized sample/onset producers remain explicit
// external interfaces. This is not the PS/RFDC board wrapper.
module calibrator_dataplane_system #(
 parameter integer PRE_SAMPLES=250,DETECTOR_LATENCY=1,FIFO_ADDR_W=12,AWG_DEPTH=16384,PHYSICAL_MASKS_IN_TEMPLATE=0
)(
 output wire pdw_valid,output wire [255:0] pdw_key,output wire [1023:0] pdw_header,output wire [511:0] pdw_stats,output wire [191:0] pdw_peaks,
 output wire [15:0] replay_leased,
 input wire  clk_rf,
 input wire  clk_mem,
 input wire  rst_n,
 input wire  arm_enable,
 input wire  reset_request,
 input wire  sample_valid,
 input wire [63:0] sample_seq,
 input wire [255:0] group_data,
 input wire  onset_valid,
 output wire  onset_ready,
 output wire  onset_accepted,
 output wire  onset_rejected,
 input wire [63:0] onset_seq,
 input wire [63:0] onset_gsc,
 input wire [63:0] onset_pulse_id,
 input wire [63:0] config_version,
 input wire [1023:0] onset_config,
 input wire [1023:0] onset_metadata,
 input wire [255:0] onset_noise,
 input wire [5:0] onset_bad_channels,
 input wire  onset_want_replay,
 input wire  eop_event_valid,
 input wire [63:0] eop_event_pulse_id,
 input wire [63:0] eop_event_owner_epoch,
 input wire [63:0] eop_event_stop,
 input wire [5:0] eop_event_bad_channels,
 output wire  eop_accepted,
 output wire  eop_rejected,
 output wire  producer_error_valid,
 output wire  producer_error_bound,
 input wire  producer_error_ready,
 output wire [255:0] producer_error_key,
 output wire [5:0] producer_error_bank_ids,
 output wire [191:0] producer_error_generations,
 output wire [7:0] producer_error_reason,
 output wire [31:0] onset_reject_count,
 output wire [31:0] eop_reject_count,
 output wire [31:0] context_error_count,
 output wire  header_error,
 output wire [7:0] statistics_error,
 output wire  disposition_valid,
 output wire  descriptor_accepted,
 output wire  disposition_rejected,
 output wire  completion_valid,
 output wire  completion_error,
 output wire [63:0] completion_epoch,
 output wire [63:0] completion_generation,
 output wire [1:0] completion_group,
 output wire [1:0] completion_bank,
 output wire [31:0] record_errors,
 output wire [31:0] rejected_returns,
 output wire [31:0] dropped_triggers,
 output wire [15:0] write_enable,
 output wire [15:0] armed,
 output wire [15:0] pending,
 output wire [15:0] frozen,
 output wire [15:0] truncated,
 output wire [15:0] qualified,
 output wire [1023:0] start_seq,
 output wire [1023:0] generation,
 output wire [1023:0] pulse_id,
 output wire [239:0] sample_count,
 output wire [63:0] owner_epoch,
 output wire  quiesce,
 output wire  idle_rf,
 output wire  primary_admitted,
 output wire  block_new_work,
 output wire  reset_busy,
 output wire  reset_done,
 output wire [127:0] m_axis_tdata,
 output wire [15:0] m_axis_tkeep,
 output wire  m_axis_tlast,
 output wire  m_axis_tvalid,
 input wire  m_axis_tready,
 output wire [FIFO_ADDR_W:0] fifo_occupancy,
 input wire  r_submit_valid,
 input wire [1535:0] r_submit_task,
 output wire  r_submit_accepted,
 output wire  r_submit_rejected,
 output wire [7:0] r_submit_reason,
 output wire  r_lookup_valid,
 output wire [1535:0] r_lookup_task,
 input wire [31:0] r_current_config_id,
 input wire [31:0] r_current_fir_id,
 input wire [31:0] r_current_source_epoch,
 input wire  r_source_stable,
 input wire  r_allow_aux_replay,
 input wire  r_task_profiles_valid,
 input wire  r_guard_clear,
 input wire  r_planned_slot_clear,
 input wire  r_resources_ready,
 input wire  r_time_valid,
 input wire  r_clock_ok,
 input wire  r_latency_validated,
 input wire  r_fractional_supported,
 input wire [63:0] r_downstream_latency_ticks,
 output wire  r_rejected_valid,
 output wire [1535:0] r_rejected_task,
 output wire [7:0] r_reject_reason,
 input wire  r_reject_ready,
 output wire  r_task_started,
 output wire [1535:0] r_active_task,
 output wire  r_raw_valid,
 output wire [63:0] r_raw_data,
 output wire  r_raw_last,
 output wire  r_ram_en,
 output wire [13:0] r_ram_addr,
 output wire [31:0] r_ram_group,
 output wire [31:0] r_ram_bank,
 output wire  r_actual_start,
 output wire  r_actual_finish,
 output wire [63:0] r_actual_start_gsc,
 output wire [63:0] r_actual_finish_gsc,
 output wire  r_token_valid,
 output wire [63:0] r_token_owner_epoch,
 output wire [63:0] r_token_generation,
 output wire [31:0] r_token_group,
 output wire [31:0] r_token_bank,
 output wire [31:0] r_token_consumer,
 output wire [7:0] r_token_status,
 output wire [31:0] r_queued_count,
 output wire  r_idle,
 input wire  r_profile_commit,
 input wire [1:0] r_shadow_cal_valid,
 input wire [63:0] r_shadow_dc,
 input wire [71:0] r_shadow_gain,
 input wire [143:0] r_shadow_matrix,
 input wire [7:0] r_shadow_fd_phase,
 input wire [31:0] r_shadow_fd_version,
 input wire [31:0] r_shadow_rx_cal_id,
 input wire [31:0] r_shadow_target_matrix_id,
 input wire [31:0] r_shadow_doppler_phase_id,
 input wire  r_phase_valid,
 input wire signed [17:0] r_phase_i,
 input wire signed [17:0] r_phase_q,
 output wire  r_profile_ready,
 output wire  r_profile_accepted,
 output wire  r_profile_rejected,
 output wire  r_source_ready,
 output wire  r_dsp_busy,
 output wire  r_dsp_done,
 output wire  r_dsp_cancelled,
 output wire [63:0] r_out_hv,
 output wire  r_out_valid,
 output wire  r_out_qualified,
 output wire  r_arithmetic_saturated,
 output wire [31:0] r_table_version,
 output wire [31:0] r_active_rx_cal_id,
 output wire [31:0] r_active_target_matrix_id,
 output wire [31:0] r_active_doppler_phase_id,
 output wire [31:0] r_active_fd_version,
 output wire [7:0] r_active_fd_phase,
 input wire  t_binding_valid,
 input wire  t_timing_valid,
 input wire  t_arm,
 input wire  t_tx_request,
 input wire  t_hard_fault,
 input wire  t_pll_locked,
 input wire  t_heartbeat,
 input wire  t_clear_fault,
 input wire  t_pa_on_fb,
 input wire  t_tr_tx_fb,
 input wire  t_rx_protected_fb,
 input wire [31:0] t_protect_cycles,
 input wire [31:0] t_switch_cycles,
 input wire [31:0] t_pa_cycles,
 input wire [31:0] t_recovery_cycles,
 input wire [31:0] t_transition_timeout_cycles,
 input wire [31:0] t_watchdog_cycles,
 output wire  t_pa_enable_req,
 output wire  t_tr_tx_req,
 output wire  t_rx_protect_req,
 output wire  t_rf_dac_mute,
 output wire  t_rf_fault,
 output wire  t_unbound,
 output wire  t_rf_permit,
 output wire [2:0] t_rf_state,
 input wire  t_stop_request,
 input wire  t_safe_boundary,
 input wire  t_mode_request,
 input wire  t_config_commit,
 input wire  t_single_antenna_ota,
 input wire [2:0] t_requested_mode,
 input wire [7:0] t_route_select,
 input wire [7:0] t_route_enable,
 input wire [7:0] t_cal_valid,
 input wire [127:0] t_dc_i,
 input wire [127:0] t_dc_q,
 input wire [143:0] t_gain_i,
 input wire [143:0] t_gain_q,
 input wire [31:0] t_config_id,
 input wire  t_dds_cmd_valid,
 input wire [63:0] t_dds_start_gsc,
 input wire [31:0] t_dds_pw_samples,
 input wire [31:0] t_dds_pri_samples,
 input wire [31:0] t_dds_pulse_count,
 input wire [47:0] t_dds_initial_pinc,
 input wire [47:0] t_dds_chirp_step,
 input wire  t_dds_reset_each_pulse,
 output wire  t_dds_accepted,
 output wire  t_dds_rejected,
 output wire  t_dds_busy,
 output wire  t_dds_done,
 input wire  t_awg_ctrl_valid,
 input wire [1:0] t_awg_ctrl_op,
 input wire [31:0] t_awg_ctrl_length,
 input wire [31:0] t_awg_ctrl_crc32c,
 input wire [63:0] t_awg_ctrl_data,
 output wire  t_awg_ctrl_ready,
 output wire  t_awg_ctrl_done,
 output wire  t_awg_ctrl_error,
 output wire  t_awg_ctrl_loaded,
 output wire  t_awg_ctrl_active_valid,
 output wire [1:0] t_awg_ctrl_done_op,
 input wire  t_awg_play,
 output wire  t_awg_play_accepted,
 output wire  t_awg_play_rejected,
 output wire  t_awg_busy,
 output wire  t_awg_done,
 output wire  t_awg_done_cancelled,
 output wire [2:0] t_active_mode,
 output wire  t_mode_accepted,
 output wire  t_mode_rejected,
 output wire  t_config_accepted,
 output wire  t_config_rejected,
 output wire  t_pipeline_ready,
 output wire  t_start_ready,
 input wire t_lifecycle_ready,output wire t_tail_empty,
 output wire  t_sources_drained,
 output wire [31:0] t_active_config_id,
 output wire [127:0] t_calibrated_i,
 output wire [127:0] t_calibrated_q,
 output wire [7:0] t_calibrated_valid,
 output wire [7:0] t_calibration_saturated,
 output wire [7:0] t_tx_saturated,
 output wire [7:0] t_native_dac_valid,
 output wire [1023:0] t_native_dac_data,
 input wire  clk_ctrl,
 input wire [63:0] gsc,
 input wire [1:0] live_range,
 input wire  live_range_valid,
 output wire [31:0] rejected_tokens
);
 import replay_control_layout_pkg::*;
 wire  ack_replay;
 wire [3:0] ack_replay_bank;
 wire [63:0] ack_replay_epoch;
 wire [63:0] ack_replay_generation;
 wire [15:0] replay_enable;
 wire [223:0] replay_address;
 wire [1023:0] replay_data;
 wire [15:0] replay_valid;
 wire rf_rst=!rst_n;
 wire [63:0] current_generation,ram_data;
 wire bank_frozen,data_ready,bank_qualified,lease_pinned,ram_response_valid,token_ready;
 wire child_submit_rejected;wire [7:0] child_submit_reason;
 reg blocked_submit;
 assign r_submit_rejected=blocked_submit||child_submit_rejected;
 assign r_submit_reason=blocked_submit?8'd2:child_submit_reason;
 always @(posedge clk_rf)if(rf_rst)blocked_submit<=0;else blocked_submit<=r_submit_valid&&block_new_work;
 reg [7:0] route_mask_pending,active_route_mask;
 always @(posedge clk_rf)begin
  if(rf_rst)begin route_mask_pending<=0;active_route_mask<=0;end
  else begin
   if(t_config_commit)route_mask_pending<=t_route_enable&t_cal_valid;
   if(t_config_accepted)active_route_mask<=route_mask_pending;
  end
 end
 reg replay_active;
 always @(posedge clk_rf)begin
  if(rf_rst)replay_active<=0;
  else begin
   if(r_task_started)replay_active<=1;
   if(r_token_valid&&token_ready)replay_active<=0;
  end
 end
 wire [63:0] live_data=(live_range<3)?group_data[live_range*64+:64]:64'd0;
 wire live_valid=sample_valid&&live_range_valid&&(live_range<3)&&!block_new_work;
 capture_replay_binding binding_adapter(
  .clk(clk_rf),.rst(rf_rst),.lookup_task(r_lookup_task),.active_task(r_active_task),.active(replay_active),
  .owner_epoch(owner_epoch),.frozen(frozen),.qualified(qualified),.replay_leased(replay_leased),
  .generation(generation),.pulse_id(pulse_id),.start_seq(start_seq),.sample_count(sample_count),
  .current_generation(current_generation),.bank_frozen(bank_frozen),.data_ready(data_ready),.bank_qualified(bank_qualified),.lease_pinned(lease_pinned),
  .ram_en(r_ram_en),.ram_group(r_ram_group),.ram_bank(r_ram_bank),.ram_addr(r_ram_addr),
  .replay_enable(replay_enable),.replay_address(replay_address),.replay_data(replay_data),.replay_valid(replay_valid),
  .ram_response_valid(ram_response_valid),.ram_data(ram_data),
  .token_valid(r_token_valid),.token_owner_epoch(r_token_owner_epoch),.token_generation(r_token_generation),
  .token_group(r_token_group),.token_bank(r_token_bank),.token_consumer(r_token_consumer),.token_ready(token_ready),
  .ack_replay(ack_replay),.ack_replay_bank(ack_replay_bank),.ack_replay_epoch(ack_replay_epoch),.ack_replay_generation(ack_replay_generation),.rejected_tokens(rejected_tokens));
 calibrator_capture_system #(.PRE_SAMPLES(PRE_SAMPLES),.DETECTOR_LATENCY(DETECTOR_LATENCY),.FIFO_ADDR_W(FIFO_ADDR_W),.PHYSICAL_MASKS_IN_TEMPLATE(PHYSICAL_MASKS_IN_TEMPLATE)) capture(
  .replay_leased(replay_leased),
  .clk_rf(clk_rf),
  .clk_mem(clk_mem),
  .rst_n(rst_n),
  .arm_enable(arm_enable),
  .reset_request(reset_request),
  .replay_quiescent(r_idle),
  .sample_valid(sample_valid),
  .sample_seq(sample_seq),
  .group_data(group_data),
  .onset_valid(onset_valid),
  .onset_ready(onset_ready),
  .onset_accepted(onset_accepted),
  .onset_rejected(onset_rejected),
  .onset_seq(onset_seq),
  .onset_gsc(onset_gsc),
  .onset_pulse_id(onset_pulse_id),
  .config_version(config_version),
  .onset_config(onset_config),
  .onset_metadata(onset_metadata),
  .onset_noise(onset_noise),
  .onset_bad_channels(onset_bad_channels),
  .onset_want_replay(onset_want_replay),
  .eop_event_valid(eop_event_valid),
  .eop_event_pulse_id(eop_event_pulse_id),
  .eop_event_owner_epoch(eop_event_owner_epoch),
  .eop_event_stop(eop_event_stop),
  .eop_event_bad_channels(eop_event_bad_channels),
  .eop_accepted(eop_accepted),
  .eop_rejected(eop_rejected),
  .producer_error_valid(producer_error_valid),
  .producer_error_bound(producer_error_bound),
  .producer_error_ready(producer_error_ready),
  .producer_error_key(producer_error_key),
  .producer_error_bank_ids(producer_error_bank_ids),
  .producer_error_generations(producer_error_generations),
  .producer_error_reason(producer_error_reason),
  .onset_reject_count(onset_reject_count),
  .eop_reject_count(eop_reject_count),
  .context_error_count(context_error_count),
  .header_error(header_error),
  .statistics_error(statistics_error),
  .pdw_valid(pdw_valid),.pdw_key(pdw_key),.pdw_header(pdw_header),.pdw_stats(pdw_stats),.pdw_peaks(pdw_peaks),
  .disposition_valid(disposition_valid),
  .descriptor_accepted(descriptor_accepted),
  .disposition_rejected(disposition_rejected),
  .ack_replay(ack_replay),
  .ack_replay_bank(ack_replay_bank),
  .ack_replay_epoch(ack_replay_epoch),
  .ack_replay_generation(ack_replay_generation),
  .replay_enable(replay_enable),
  .replay_address(replay_address),
  .replay_data(replay_data),
  .replay_valid(replay_valid),
  .completion_valid(completion_valid),
  .completion_error(completion_error),
  .completion_epoch(completion_epoch),
  .completion_generation(completion_generation),
  .completion_group(completion_group),
  .completion_bank(completion_bank),
  .record_errors(record_errors),
  .rejected_returns(rejected_returns),
  .dropped_triggers(dropped_triggers),
  .write_enable(write_enable),
  .armed(armed),
  .pending(pending),
  .frozen(frozen),
  .truncated(truncated),
  .qualified(qualified),
  .start_seq(start_seq),
  .generation(generation),
  .pulse_id(pulse_id),
  .sample_count(sample_count),
  .owner_epoch(owner_epoch),
  .quiesce(quiesce),
  .idle_rf(idle_rf),
  .primary_admitted(primary_admitted),
  .block_new_work(block_new_work),
  .reset_busy(reset_busy),
  .reset_done(reset_done),
  .m_axis_tdata(m_axis_tdata),
  .m_axis_tkeep(m_axis_tkeep),
  .m_axis_tlast(m_axis_tlast),
  .m_axis_tvalid(m_axis_tvalid),
  .m_axis_tready(m_axis_tready),
  .fifo_occupancy(fifo_occupancy)
 );
 calibrator_replay_system  replay(
  .clk(clk_rf),
  .rst(rf_rst),
  .submit_valid(r_submit_valid&&!block_new_work),
  .submit_task(r_submit_task),
  .submit_accepted(r_submit_accepted),
  .submit_rejected(child_submit_rejected),
  .submit_reason(child_submit_reason),
  .lookup_valid(r_lookup_valid),
  .lookup_task(r_lookup_task),
  .lookup_ready(!replay_active),
  .gsc(gsc),
  .current_owner_epoch(owner_epoch),
  .current_generation(current_generation),
  .current_config_id(r_current_config_id),
  .current_fir_id(r_current_fir_id),
  .current_source_epoch(r_current_source_epoch),
  .bank_frozen(bank_frozen),
  .data_ready(data_ready),
  .qualified(bank_qualified),
  .lease_pinned(lease_pinned),
  .source_stable(r_source_stable),
  .allow_aux_replay(r_allow_aux_replay),
  .task_profiles_valid(r_task_profiles_valid&&r_lookup_task[OUTPUT_DAC_MASK_BIT+:32]=={24'd0,active_route_mask}),
  .guard_clear(r_guard_clear),
  .planned_slot_clear(r_planned_slot_clear),
  .rf_safe(t_rf_permit&&t_pipeline_ready&&t_active_mode==2&&!block_new_work&&!t_stop_request&&!t_mode_request&&!t_config_commit),
  .binding_valid(t_binding_valid),
  .resources_ready(r_resources_ready),
  .time_valid(r_time_valid),
  .clock_ok(r_clock_ok),
  .latency_validated(r_latency_validated),
  .fractional_supported(r_fractional_supported),
  .downstream_latency_ticks(r_downstream_latency_ticks),
  .hard_fault(t_hard_fault||t_rf_fault),
  .abort_request(block_new_work||t_stop_request),
  .rejected_valid(r_rejected_valid),
  .rejected_task(r_rejected_task),
  .reject_reason(r_reject_reason),
  .reject_ready(r_reject_ready),
  .task_started(r_task_started),
  .active_task(r_active_task),
  .raw_valid(r_raw_valid),
  .raw_data(r_raw_data),
  .raw_last(r_raw_last),
  .ram_en(r_ram_en),
  .ram_addr(r_ram_addr),
  .ram_group(r_ram_group),
  .ram_bank(r_ram_bank),
  .ram_response_valid(ram_response_valid),
  .ram_data(ram_data),
  .actual_start(r_actual_start),
  .actual_finish(r_actual_finish),
  .actual_start_gsc(r_actual_start_gsc),
  .actual_finish_gsc(r_actual_finish_gsc),
  .token_valid(r_token_valid),
  .token_ready(token_ready),
  .token_owner_epoch(r_token_owner_epoch),
  .token_generation(r_token_generation),
  .token_group(r_token_group),
  .token_bank(r_token_bank),
  .token_consumer(r_token_consumer),
  .token_status(r_token_status),
  .queued_count(r_queued_count),
  .idle(r_idle),
  .profile_commit(r_profile_commit),
  .shadow_cal_valid(r_shadow_cal_valid),
  .shadow_dc(r_shadow_dc),
  .shadow_gain(r_shadow_gain),
  .shadow_matrix(r_shadow_matrix),
  .shadow_fd_phase(r_shadow_fd_phase),
  .shadow_fd_version(r_shadow_fd_version),
  .shadow_rx_cal_id(r_shadow_rx_cal_id),
  .shadow_target_matrix_id(r_shadow_target_matrix_id),
  .shadow_doppler_phase_id(r_shadow_doppler_phase_id),
  .phase_valid(r_phase_valid),
  .phase_i(r_phase_i),
  .phase_q(r_phase_q),
  .profile_ready(r_profile_ready),
  .profile_accepted(r_profile_accepted),
  .profile_rejected(r_profile_rejected),
  .source_ready(r_source_ready),
  .dsp_busy(r_dsp_busy),
  .dsp_done(r_dsp_done),
  .dsp_cancelled(r_dsp_cancelled),
  .out_hv(r_out_hv),
  .out_valid(r_out_valid),
  .out_qualified(r_out_qualified),
  .arithmetic_saturated(r_arithmetic_saturated),
  .table_version(r_table_version),
  .active_rx_cal_id(r_active_rx_cal_id),
  .active_target_matrix_id(r_active_target_matrix_id),
  .active_doppler_phase_id(r_active_doppler_phase_id),
  .active_fd_version(r_active_fd_version),
  .active_fd_phase(r_active_fd_phase)
 );
 calibrator_transmit_system #(.AWG_DEPTH(AWG_DEPTH)) transmit(
  .clk_rf(clk_rf),
  .clk_ctrl(clk_ctrl),
  .rst_n(rst_n),
  .binding_valid(t_binding_valid),
  .timing_valid(t_timing_valid),
  .arm(t_arm),
  .tx_request(t_tx_request),
  .hard_fault(t_hard_fault),
  .pll_locked(t_pll_locked),
  .heartbeat(t_heartbeat),
  .clear_fault(t_clear_fault),
  .pa_on_fb(t_pa_on_fb),
  .tr_tx_fb(t_tr_tx_fb),
  .rx_protected_fb(t_rx_protected_fb),
  .protect_cycles(t_protect_cycles),
  .switch_cycles(t_switch_cycles),
  .pa_cycles(t_pa_cycles),
  .recovery_cycles(t_recovery_cycles),
  .transition_timeout_cycles(t_transition_timeout_cycles),
  .watchdog_cycles(t_watchdog_cycles),
  .pa_enable_req(t_pa_enable_req),
  .tr_tx_req(t_tr_tx_req),
  .rx_protect_req(t_rx_protect_req),
  .rf_dac_mute(t_rf_dac_mute),
  .rf_fault(t_rf_fault),
  .unbound(t_unbound),
  .rf_permit(t_rf_permit),
  .rf_state(t_rf_state),
  .stop_request(t_stop_request),
  .safe_boundary(t_safe_boundary),
  .mode_request(t_mode_request),
  .config_commit(t_config_commit),
  .single_antenna_ota(t_single_antenna_ota),
  .requested_mode(t_requested_mode),
  .route_select(t_route_select),
  .route_enable(t_route_enable),
  .cal_valid(t_cal_valid),
  .dc_i(t_dc_i),
  .dc_q(t_dc_q),
  .gain_i(t_gain_i),
  .gain_q(t_gain_q),
  .config_id(t_config_id),
  .live_data(live_data),
  .drfm_data(r_out_hv),
  .live_valid(live_valid),
  .drfm_valid(r_out_valid&&r_out_qualified),
  .gsc(gsc),
  .dds_cmd_valid(t_dds_cmd_valid),
  .dds_start_gsc(t_dds_start_gsc),
  .dds_pw_samples(t_dds_pw_samples),
  .dds_pri_samples(t_dds_pri_samples),
  .dds_pulse_count(t_dds_pulse_count),
  .dds_initial_pinc(t_dds_initial_pinc),
  .dds_chirp_step(t_dds_chirp_step),
  .dds_reset_each_pulse(t_dds_reset_each_pulse),
  .dds_accepted(t_dds_accepted),
  .dds_rejected(t_dds_rejected),
  .dds_busy(t_dds_busy),
  .dds_done(t_dds_done),
  .awg_ctrl_valid(t_awg_ctrl_valid),
  .awg_ctrl_op(t_awg_ctrl_op),
  .awg_ctrl_length(t_awg_ctrl_length),
  .awg_ctrl_crc32c(t_awg_ctrl_crc32c),
  .awg_ctrl_data(t_awg_ctrl_data),
  .awg_ctrl_ready(t_awg_ctrl_ready),
  .awg_ctrl_done(t_awg_ctrl_done),
  .awg_ctrl_error(t_awg_ctrl_error),
  .awg_ctrl_loaded(t_awg_ctrl_loaded),
  .awg_ctrl_active_valid(t_awg_ctrl_active_valid),
  .awg_ctrl_done_op(t_awg_ctrl_done_op),
  .awg_play(t_awg_play),
  .awg_play_accepted(t_awg_play_accepted),
  .awg_play_rejected(t_awg_play_rejected),
  .awg_busy(t_awg_busy),
  .awg_done(t_awg_done),
  .awg_done_cancelled(t_awg_done_cancelled),
  .active_mode(t_active_mode),
  .mode_accepted(t_mode_accepted),
  .mode_rejected(t_mode_rejected),
  .config_accepted(t_config_accepted),
  .config_rejected(t_config_rejected),
  .pipeline_ready(t_pipeline_ready),
  .start_ready(t_start_ready),
  .sources_drained(t_sources_drained),.lifecycle_ready(t_lifecycle_ready),.tail_empty(t_tail_empty),
  .active_config_id(t_active_config_id),
  .calibrated_i(t_calibrated_i),
  .calibrated_q(t_calibrated_q),
  .calibrated_valid(t_calibrated_valid),
  .calibration_saturated(t_calibration_saturated),
  .tx_saturated(t_tx_saturated),
  .native_dac_valid(t_native_dac_valid),
  .native_dac_data(t_native_dac_data)
 );
endmodule
